package com.noesis.domain.constants;

public enum ErrorCodesEnum {

	INSUFFICIENT_BALANCE("101","INSUFFICIENT_BALANCE"),
	MESSAGE_RECEIVED_POST_CUT_OFF("102","MESSAGE_RECEIVED_POST_CUT_OFF"),
	DND_NUMBER_FOUND("103","DND_NUMBER_FOUND"),
	RESTRICTED_CONTENT_FOUND("104","RESTRICTED_CONTENT_FOUND"),
	INVALID_SENDER_ID("105","INVALID_SENDER_ID"),
	USER_BLACK_LIST_NUMBER_FOUND("106","USER_BLACK_LIST_NUMBER_FOUND"),
	GLOBAL_BLACK_LIST_NUMBER_FOUND("107","GLOBAL_BLACK_LIST_NUMBER_FOUND"),
	USER_BLACK_LIST_SENDER_ID_FOUND("108","USER_BLACK_LIST_SENDER_ID_FOUND"),
	GLOBAL_BLACK_LIST_SENDER_ID_FOUND("109","GLOBAL_BLACK_LIST_SENDER_ID_FOUND"),
	INVALID_DESTINATION_NUMBER("110","INVALID_DESTINATION_NUMBER"),
	NO_ACTIVE_KANNEL_FOUND("111","NO_ACTIVE_KANNEL_FOUND"),
	KANNEL_NOT_REACHABLE("112","KANNEL_NOT_REACHABLE"),
	CONTENT_TEMPLATE_MISMATCH("113", "CONTENT_TEMPLATE_MISMATCH"),
	FAILED_NUMBER_FOUND("120","FAILED_NUMBER_FOUND"),
	// API ERROR CODES
	INACTIVE_USER("113","INACTIVE_USER"),
	INVALID_API_KEY("114","INVALID_API_KEY"),
	INVALID_MESSAGE_TYPE("116","INVALID_MESSAGE_TYPE"),
	INVALID_MESSAGE_TEXT("117","INVALID_MESSAGE_TEXT"),
	INVALID_USER("118","INVALID_USER");
	
	private ErrorCodesEnum( String errorCode,String errorDesc) {
		this.errorDesc = errorDesc;
		this.errorCode = errorCode;
	}
	
	private final String errorDesc;
	
	private final String errorCode;
	
	public String getErrorDesc() {
		return errorDesc;
	}
	
	public String getErrorCode() {
		return errorCode;
	}
}
