package com.noesis.domain.persistence;
// Generated 15 Jan, 2019 12:21:17 AM by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * NgAbusingWordsCategory generated by hbm2java
 */
@Entity
@Table(name = "ng_abusing_words_category", catalog = "genesis")
public class NgAbusingWordsCategory implements java.io.Serializable {

	private String category;
	private int id;

	public NgAbusingWordsCategory() {
	}

	public NgAbusingWordsCategory(String category, int id) {
		this.category = category;
		this.id = id;
	}

	@Id

	@Column(name = "category", unique = true, nullable = false, length = 100)
	public String getCategory() {
		return this.category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	@Column(name = "id", nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

}
