package com.noesis.domain.persistence;
// Generated 31 Jul, 2018 12:08:37 AM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * NgUserRole generated by hbm2java
 */
@Entity
@Table(name = "ng_abusing_words_list", catalog = "genesis")
public class NgAbusingWordsList implements java.io.Serializable {

	private static final long serialVersionUID = 6183408858933902776L;
	private String abusingWord;
	private String abusingWordCatagory;
	
	public NgAbusingWordsList() {
	}

	public NgAbusingWordsList(String abusingWord) {
		this.abusingWord = abusingWord;
	}

	public NgAbusingWordsList(String abusingWord, String abusingWordCatagory) {
		this.abusingWord = abusingWord;
		this.abusingWordCatagory = abusingWordCatagory;
	}

	@Id
	@Column(name = "abusing_word", unique = true, nullable = false)
	public String getAbusingWord() {
		return abusingWord;
	}

	public void setAbusingWord(String abusingWord) {
		this.abusingWord = abusingWord;
	}

	@Column(name = "abusing_word_category", length = 45)
	public String getAbusingWordCatagory() {
		return abusingWordCatagory;
	}

	public void setAbusingWordCatagory(String abusingWordCatagory) {
		this.abusingWordCatagory = abusingWordCatagory;
	}
	
	

}
