package com.noesis.domain.persistence;
// Generated 18 Dec, 2018 8:18:51 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NgKannelInfo generated by hbm2java
 */
@Entity
@Table(name = "ng_analytics_curr_date", catalog = "genesis")
public class NgAnalyticsCurrDate implements java.io.Serializable {
	
	private static final long serialVersionUID = 1676665425599676769L;
	private int id;
	private int userId;
	private Integer parentShortUrlId;
	private String parentShortUrl;
	private String childShortUrl;
	private String mobileNumber;
	private Integer campaignId;
	private String campaignName;
	private Date createdDate;
	private Date updatedDate;
	private Date currDate;
	private String userIpAddress;
	private String browserDetails;
	private String operatingSystem;
	private String deviceDetails;
	private String completeHeader;
	private String country;
	private String region;
	private String city;
	private Integer zip;
	private String longUrl;
	
	public NgAnalyticsCurrDate() {
	}

	public NgAnalyticsCurrDate(int id, int userId, Integer parentShortUrlId, String parentShortUrl, String childShortUrl, 
			String mobileNumber, Integer campaignId, String campaignName, Date createdDate, Date updatedDate, Date currDate,
			String userIpAddress, String browserDetails, String operatingSystem, String deviceDetails, String completeHeader,
			String country, String region, String city, Integer zip, String longUrl) {
		this.id = id;
		this.userId = userId;
		this.parentShortUrlId = parentShortUrlId;
		this.parentShortUrl = parentShortUrl;
		this.childShortUrl = childShortUrl;
		this.mobileNumber = mobileNumber;
		this.campaignId = campaignId;
		this.campaignName = campaignName;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
		this.currDate = currDate;
		this.userIpAddress = userIpAddress;
		this.browserDetails = browserDetails;
		this.operatingSystem = operatingSystem;
		this.deviceDetails = deviceDetails;
		this.completeHeader = completeHeader;
		this.country = country;
		this.region = region;
		this.city = city;
		this.zip = zip;
		this.longUrl = longUrl;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}
	
	@Column(name = "userId", unique = true, nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}
	
	@Column(name = "parent_short_url_id", unique = true, nullable = false, length = 100)
	public Integer getParentShortUrlId() {
		return this.parentShortUrlId;
	}

	public void setParentShortUrlId(Integer parentShortUrlId) {
		this.parentShortUrlId = parentShortUrlId;
	}

	@Column(name = "parent_short_url", nullable = false, length = 100)
	public String getParentShortUrl() {
		return this.parentShortUrl;
	}

	public void setParentShortUrl(String parentShortUrl) {
		this.parentShortUrl = parentShortUrl;
	}
	
	@Column(name = "child_short_url", nullable = false, length = 100)
	public String getChildShortUrl() {
		return this.childShortUrl;
	}

	public void setChildShortUrl(String childShortUrl) {
		this.childShortUrl = childShortUrl;
	}
	
	@Column(name = "mobile_number", nullable = false, length = 20)
	public String getMobileNumber() {
		return this.mobileNumber;
	}

	public void setMobileNumber(String mobileNumber) {
		this.mobileNumber = mobileNumber;
	}
	
	@Column(name = "campaign_id", nullable = false, length = 100)
	public Integer getCampaignId() {
		return this.campaignId;
	}

	public void setCampaignId(Integer campaignId) {
		this.campaignId = campaignId;
	}
	
	@Column(name = "campaign_name", nullable = false, length = 100)
	public String getCampaignName() {
		return this.campaignName;
	}

	public void setCampaignName(String campaignName) {
		this.campaignName = campaignName;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", nullable = false, length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_date", nullable = false, length = 19)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "curr_date", nullable = false, length = 19)
	public Date getCurrDate() {
		return this.currDate;
	}

	public void setCurrDate(Date currDate) {
		this.currDate = currDate;
	}
	
	@Column(name = "user_ip_address", nullable = false, length = 30)
	public String getUserIpAddress() {
		return this.userIpAddress;
	}

	public void setUserIpAddress(String userIpAddress) {
		this.userIpAddress = userIpAddress;
	}
	
	@Column(name = "browser_details", nullable = false, length = 100)
	public String getBrowserDetails() {
		return this.browserDetails;
	}

	public void setBrowserDetails(String browserDetails) {
		this.browserDetails = browserDetails;
	}
	
	@Column(name = "operating_system", nullable = false, length = 100)
	public String getOperatingSystem() {
		return this.operatingSystem;
	}

	public void setOperatingSystem(String operatingSystem) {
		this.operatingSystem = operatingSystem;
	}
	
	@Column(name = "device_details", nullable = false, length = 100)
	public String getDeviceDetails() {
		return this.deviceDetails;
	}

	public void setDeviceDetails(String deviceDetails) {
		this.deviceDetails = deviceDetails;
	}
	
	@Column(name = "complete_header", nullable = false, length = 1000)
	public String getCompleteHeader() {
		return this.completeHeader;
	}

	public void setCompleteHeader(String completeHeader) {
		this.completeHeader = completeHeader;
	}
	
	@Column(name = "country", nullable = false, length = 50)
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}
	
	@Column(name = "region", nullable = false, length = 50)
	public String getRegion() {
		return this.region;
	}

	public void setRegion(String region) {
		this.region = region;
	}
	
	@Column(name = "city", nullable = false, length = 50)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}
	
	@Column(name = "zip", nullable = false, length = 11)
	public Integer getZip() {
		return this.zip;
	}

	public void setZip(Integer zip) {
		this.zip = zip;
	}

	@Column(name = "long_url")
	public String getLongUrl() {
		return longUrl;
	}

	public void setLongUrl(String longUrl) {
		this.longUrl = longUrl;
	}
	
	

}
