package com.noesis.domain.persistence;
// Generated 21 Aug, 2018 4:46:47 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * NgCarrierErrorMaster generated by hbm2java
 */
@Entity
@Table(name = "ng_carrier_error_master", catalog = "genesis")
public class NgCarrierErrorMaster implements java.io.Serializable {

	private Integer id;
	private Integer errorCode;
	private String errorDesc;
	private String smscId;
	private String carrierError;
	private String carrierErrorDesc;
	private String carrierStat;
	private Integer isDlrRetry;

	public NgCarrierErrorMaster() {
	}

	public NgCarrierErrorMaster(Integer errorCode, String errorDesc, String smscId, String carrierError,
			String carrierErrorDesc, String carrierStat, Integer isDlrRetry) {
		this.errorCode = errorCode;
		this.errorDesc = errorDesc;
		this.smscId = smscId;
		this.carrierError = carrierError;
		this.carrierErrorDesc = carrierErrorDesc;
		this.carrierStat = carrierStat;
		this.isDlrRetry = isDlrRetry;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "error_code")
	public Integer getErrorCode() {
		return this.errorCode;
	}

	public void setErrorCode(Integer errorCode) {
		this.errorCode = errorCode;
	}

	@Column(name = "error_desc", length = 50)
	public String getErrorDesc() {
		return this.errorDesc;
	}

	public void setErrorDesc(String errorDesc) {
		this.errorDesc = errorDesc;
	}

	@Column(name = "smsc_id", length = 15)
	public String getSmscId() {
		return this.smscId;
	}

	public void setSmscId(String smscId) {
		this.smscId = smscId;
	}

	@Column(name = "carrier_error", length = 10)
	public String getCarrierError() {
		return this.carrierError;
	}

	public void setCarrierError(String carrierError) {
		this.carrierError = carrierError;
	}

	@Column(name = "carrier_error_desc", length = 50)
	public String getCarrierErrorDesc() {
		return this.carrierErrorDesc;
	}

	public void setCarrierErrorDesc(String carrierErrorDesc) {
		this.carrierErrorDesc = carrierErrorDesc;
	}

	@Column(name = "carrier_stat", length = 15)
	public String getCarrierStat() {
		return this.carrierStat;
	}

	public void setCarrierStat(String carrierStat) {
		this.carrierStat = carrierStat;
	}

	@Column(name = "is_dlr_retry")
	public Integer getIsDlrRetry() {
		return this.isDlrRetry;
	}

	public void setIsDlrRetry(Integer isDlrRetry) {
		this.isDlrRetry = isDlrRetry;
	}

}
