package com.noesis.domain.persistence;
// Generated 18 Dec, 2018 8:18:51 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NgKannelInfo generated by hbm2java
 */
@Entity
@Table(name = "ng_campaign_info", catalog = "genesis")
public class NgCampaignInfo implements java.io.Serializable {
	
	private static final long serialVersionUID = 1676665425599676769L;
	private int id;
	private int userId;
	private String campaignName;
	private String campaignType;
	private Date createdDate;
	private String sourceSystem;
	private String campaignHour;
	private String campaignMin;

	public NgCampaignInfo() {
	}

	public NgCampaignInfo(int id, int userId, String campaignName , String campaignType, Date createdDate, String sourceSystem, String campaignHour, String campaignMin) {
		
		this.id = id;
		this.userId = userId;
		this.campaignName = campaignName;
		this.campaignType = campaignType;
		this.createdDate = createdDate;
		this.sourceSystem = sourceSystem;
		this.campaignHour = campaignHour;
		this.campaignMin = campaignMin;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}
	
	@Column(name = "userId", unique = true, nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}
	
	@Column(name = "campaign_name", nullable = false, length = 100)
	public String getCampaignName() {
		return this.campaignName;
	}

	public void setCampaignName(String campaignName) {
		this.campaignName = campaignName;
	}
	
	@Column(name = "campaign_type", nullable = false, length = 50)
	public String getCampaignType() {
		return this.campaignType;
	}

	public void setCampaignType(String campaignType) {
		this.campaignType = campaignType;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", nullable = false, length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}
	
	@Column(name = "source_system", nullable = false, length = 50)
	public String getSourceSystem() {
		return this.sourceSystem;
	}

	public void setSourceSystem(String sourceSystem) {
		this.sourceSystem = sourceSystem;
	}

	@Column(name = "campaign_hour")
	public String getCampaignHour() {
		return campaignHour;
	}

	public void setCampaignHour(String campaignHour) {
		this.campaignHour = campaignHour;
	}

	@Column(name = "campaign_min")
	public String getCampaignMin() {
		return campaignMin;
	}

	public void setCampaignMin(String campaignMin) {
		this.campaignMin = campaignMin;
	}
	
	
}
