package com.noesis.domain.persistence;
// Generated 13 Dec, 2018 1:40:39 AM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * NgCarrierMaster generated by hbm2java
 */
@Entity
@Table(name = "ng_carrier_master", catalog = "genesis")
public class NgCarrierMaster implements java.io.Serializable {

	private int id;
	private String carrierName;
	private NgNumberCarrierCircleMapping ngNumberCarrierCircleMapping;

	public NgCarrierMaster() {
	}

	public NgCarrierMaster(int id, String carrierName) {
		this.id = id;
		this.carrierName = carrierName;
	}

	public NgCarrierMaster(int id, String carrierName, NgNumberCarrierCircleMapping ngNumberCarrierCircleMapping) {
		this.id = id;
		this.carrierName = carrierName;
		this.ngNumberCarrierCircleMapping = ngNumberCarrierCircleMapping;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "carrier_name", nullable = false, length = 100)
	public String getCarrierName() {
		return this.carrierName;
	}

	public void setCarrierName(String carrierName) {
		this.carrierName = carrierName;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "ngCarrierMaster")
	public NgNumberCarrierCircleMapping getNgNumberCarrierCircleMapping() {
		return this.ngNumberCarrierCircleMapping;
	}

	public void setNgNumberCarrierCircleMapping(NgNumberCarrierCircleMapping ngNumberCarrierCircleMapping) {
		this.ngNumberCarrierCircleMapping = ngNumberCarrierCircleMapping;
	}

}
