package com.noesis.domain.persistence;
// Generated 13 Dec, 2018 1:40:39 AM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * NgCircleMaster generated by hbm2java
 */
@Entity
@Table(name = "ng_circle_master", catalog = "genesis")
public class NgCircleMaster implements java.io.Serializable {

	private int id;
	private String circleName;
	private NgNumberCarrierCircleMapping ngNumberCarrierCircleMapping;

	public NgCircleMaster() {
	}

	public NgCircleMaster(int id) {
		this.id = id;
	}

	public NgCircleMaster(int id, String circleName, NgNumberCarrierCircleMapping ngNumberCarrierCircleMapping) {
		this.id = id;
		this.circleName = circleName;
		this.ngNumberCarrierCircleMapping = ngNumberCarrierCircleMapping;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "circle_name", length = 100)
	public String getCircleName() {
		return this.circleName;
	}

	public void setCircleName(String circleName) {
		this.circleName = circleName;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "ngCarrierMaster")
	public NgNumberCarrierCircleMapping getNgNumberCarrierCircleMapping() {
		return this.ngNumberCarrierCircleMapping;
	}

	public void setNgNumberCarrierCircleMapping(NgNumberCarrierCircleMapping ngNumberCarrierCircleMapping) {
		this.ngNumberCarrierCircleMapping = ngNumberCarrierCircleMapping;
	}

}
