package com.noesis.domain.persistence;
// Generated 11 Feb, 2019 12:48:00 AM by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.Set;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * NgTemplate generated by hbm2java
 */
@Entity
@Table(name = "ng_content_template", catalog = "genesis")
public class NgContentTemplate implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer id;
	private String dltTemplateId;
	private String senderId;
	private String templateName;
	private String templateDesc;
	private Integer variableCount;
	private String templateType;
	private String templateText;
	private NgUser ngUser;
	private char status;
	private Date createdDate;
	private Date updatedDate;
	private Set<NgTemplateMessageInfo> ngTemplateMessageInfoList;
	private NgServiceType ngServiceType;
	private NgServiceSubType ngServiceSubType;
	private String entityId;
	private String category;
	private String originalTemplateText;
	
	public NgContentTemplate() {
	}

	public NgContentTemplate(Integer id, String dltTemplateId, String senderId, String templateName, String templateDesc, 
			Integer variableCount, String templateType, String templateText, NgUser ngUser, char status, Date createdDate, 
			Date updatedDate, Set<NgTemplateMessageInfo> ngTemplateMessageInfoList, NgServiceType ngServiceType, NgServiceSubType ngServiceSubType,
			String entityId, String category, String originalTemplateText) {
		this.id = id;
		this.dltTemplateId = dltTemplateId;
		this.senderId = senderId;
		this.templateName = templateName;
		this.templateDesc = templateDesc;
		this.variableCount = variableCount;
		this.templateType = templateType;
		this.templateText = templateText;
		this.ngUser = ngUser;
		this.status = status;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
		this.ngTemplateMessageInfoList = ngTemplateMessageInfoList;
		this.ngServiceType = ngServiceType;
		this.ngServiceSubType = ngServiceSubType;
		this.entityId = entityId;
		this.category = category;
		this.originalTemplateText = originalTemplateText;
	}

	public NgContentTemplate(NgContentTemplate ngContentTemplate) {
		this.dltTemplateId = ngContentTemplate.dltTemplateId;
		this.senderId = ngContentTemplate.senderId;
		this.templateName = ngContentTemplate.templateName;
		this.templateDesc = ngContentTemplate.templateDesc;
		this.variableCount = ngContentTemplate.variableCount;
		this.templateType = ngContentTemplate.templateType;
		this.templateText = ngContentTemplate.templateText;
		this.ngUser = ngContentTemplate.ngUser;
		this.status = ngContentTemplate.status;
		this.createdDate = ngContentTemplate.createdDate;
		this.updatedDate = ngContentTemplate.updatedDate;
		this.ngTemplateMessageInfoList = ngContentTemplate.ngTemplateMessageInfoList;
		this.ngServiceType = ngContentTemplate.ngServiceType;
		this.ngServiceSubType = ngContentTemplate.ngServiceSubType;
		this.entityId = ngContentTemplate.entityId;
		this.category = ngContentTemplate.category;
		this.originalTemplateText = ngContentTemplate.originalTemplateText;
	}
	
	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "dlt_template_id", unique = true, nullable = false)
	public String getDltTemplateId() {
		return this.dltTemplateId;
	}

	public void setDltTemplateId(String dltTemplateId) {
		this.dltTemplateId = dltTemplateId;
	}
	
	@Column(name = "sender_id", length = 100)
	public String getSenderId() {
		return this.senderId;
	}

	public void setSenderId(String senderId) {
		this.senderId = senderId;
	}

	@Column(name = "template_name", length = 100)
	public String getTemplateName() {
		return this.templateName;
	}

	public void setTemplateName(String templateName) {
		this.templateName = templateName;
	}

	@Column(name = "template_desc", length = 250)
	public String getTemplateDesc() {
		return this.templateDesc;
	}

	public void setTemplateDesc(String templateDesc) {
		this.templateDesc = templateDesc;
	}
	
	@Column(name = "variable_count", length = 50)
	public int getVariableCount() {
		return this.variableCount;
	}

	public void setVariableCount(int variableCount) {
		this.variableCount = variableCount;
	}
	
	@Column(name = "template_type", length = 2)
	public String getTemplateType() {
		return this.templateType;
	}

	public void setTemplateType(String templateType) {
		this.templateType = templateType;
	}

	@Column(name = "template_text", length = 2500)
	public String getTemplateText() {
		return this.templateText;
	}

	public void setTemplateText(String templateText) {
		this.templateText = templateText;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false, updatable = false, insertable = true)
	@JsonBackReference
	public NgUser getNgUser() {
		return this.ngUser;
	}

	public void setNgUser(NgUser ngUser) {
		this.ngUser = ngUser;
	}
	
	@Column(name = "status", length = 250)
	public char getStatus() {
		return this.status;
	}

	public void setStatus(char status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", length = 19)
	public Date getCreatedDate() {
		return createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_date", length = 19)
	public Date getUpdatedDate() {
		return updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "ngTemplate")
	@JsonIgnore
	public Set<NgTemplateMessageInfo> getNgTemplateMessageInfoList() {
		return this.ngTemplateMessageInfoList;
	}

	public void setNgTemplateMessageInfoList(Set<NgTemplateMessageInfo> ngTemplateMessageInfoList) {
		this.ngTemplateMessageInfoList = ngTemplateMessageInfoList;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "content_template_type", nullable = false, updatable = false, insertable = true)
	@JsonBackReference
	public NgServiceType getNgServiceType() {
		return this.ngServiceType;
	}

	public void setNgServiceType(NgServiceType ngServiceType) {
		this.ngServiceType = ngServiceType;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "content_template_sub_type", nullable = false, updatable = false, insertable = true)
	@JsonBackReference
	public NgServiceSubType getNgServiceSubType() {
		return this.ngServiceSubType;
	}

	public void setNgServiceSubType(NgServiceSubType ngServiceSubType) {
		this.ngServiceSubType = ngServiceSubType;
	}

	@Column(name = "entity_id", length = 100)
	public String getEntityId() {
		return entityId;
	}

	public void setEntityId(String entityId) {
		this.entityId = entityId;
	}
	
	@Column(name = "category", length = 50)
	public String getCategory() {
		return category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	@Column(name = "original_template_text", length = 2500)
	public String getOriginalTemplateText() {
		return this.originalTemplateText;
	}

	public void setOriginalTemplateText(String originalTemplateText) {
		this.originalTemplateText = originalTemplateText;
	}
}
