package com.noesis.domain.persistence;
// Generated 31 Jul, 2018 12:08:37 AM by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * NgCustomerType generated by hbm2java
 */
@Entity
@Table(name = "ng_customer_type", catalog = "genesis")
public class NgCustomerType implements java.io.Serializable {

	private static final long serialVersionUID = 6566073490005497472L;
	private int id;
	private String custType;
	private String displayName;
	private String description;
	private Set<NgUser> ngUsers = new HashSet<NgUser>(0);

	public NgCustomerType() {
	}

	public NgCustomerType(int id) {
		this.id = id;
	}

	public NgCustomerType(int id, String custType, String displayName, String description, Set<NgUser> ngUsers) {
		this.id = id;
		this.custType = custType;
		this.displayName = displayName;
		this.description = description;
		this.ngUsers = ngUsers;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "cust_type", length = 45)
	public String getCustType() {
		return this.custType;
	}

	public void setCustType(String custType) {
		this.custType = custType;
	}

	@Column(name = "display_name", length = 45)
	public String getDisplayName() {
		return this.displayName;
	}

	public void setDisplayName(String displayName) {
		this.displayName = displayName;
	}

	@Column(name = "description", length = 45)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ngCustomerType")
	public Set<NgUser> getNgUsers() {
		return this.ngUsers;
	}

	public void setNgUsers(Set<NgUser> ngUsers) {
		this.ngUsers = ngUsers;
	}

}
