package com.noesis.domain.persistence;
// Generated 31 Jul, 2018 12:08:37 AM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;

/**
 * NgDepartment generated by hbm2java
 */
@Entity
@Table(name = "ng_department", catalog = "genesis", uniqueConstraints = @UniqueConstraint(columnNames = "version"))
public class NgDepartment implements java.io.Serializable {

	private static final long serialVersionUID = 736475903047540728L;
	private Integer id;
	private int version;
	private NgOrganisation ngOrganisation;
	private NgStatus ngStatus;
	private String deptName;
	private String email;
	private String mobile;
	private Date createdDate;
	private Date updatedDate;
	private String updatedBy;
	private Set<NgUser> ngUsers = new HashSet<NgUser>(0);

	public NgDepartment() {
	}

	public NgDepartment(NgOrganisation ngOrganisation, NgStatus ngStatus) {
		this.ngOrganisation = ngOrganisation;
		this.ngStatus = ngStatus;
	}

	public NgDepartment(NgOrganisation ngOrganisation, NgStatus ngStatus, String deptName, String email, String mobile,
			Date createdDate, Date updatedDate, String updatedBy, Set<NgUser> ngUsers) {
		this.ngOrganisation = ngOrganisation;
		this.ngStatus = ngStatus;
		this.deptName = deptName;
		this.email = email;
		this.mobile = mobile;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
		this.updatedBy = updatedBy;
		this.ngUsers = ngUsers;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Version
	@Column(name = "version", unique = true, nullable = false)
	public int getVersion() {
		return this.version;
	}

	public void setVersion(int version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "org_id", nullable = false)
	public NgOrganisation getNgOrganisation() {
		return this.ngOrganisation;
	}

	public void setNgOrganisation(NgOrganisation ngOrganisation) {
		this.ngOrganisation = ngOrganisation;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "status", nullable = false)
	public NgStatus getNgStatus() {
		return this.ngStatus;
	}

	public void setNgStatus(NgStatus ngStatus) {
		this.ngStatus = ngStatus;
	}

	@Column(name = "dept_name", length = 45)
	public String getDeptName() {
		return this.deptName;
	}

	public void setDeptName(String deptName) {
		this.deptName = deptName;
	}

	@Column(name = "email", length = 45)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "mobile", length = 45)
	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_date", length = 19)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@Column(name = "updated_by", length = 45)
	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ngDepartment")
	public Set<NgUser> getNgUsers() {
		return this.ngUsers;
	}

	public void setNgUsers(Set<NgUser> ngUsers) {
		this.ngUsers = ngUsers;
	}

}
