package com.noesis.domain.persistence;
// Generated 26 Nov, 2018 9:56:21 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NgDlrFailed generated by hbm2java
 */
@Entity
@Table(name = "ng_dlr_failed", catalog = "genesis")
public class NgDlrFailed implements java.io.Serializable {

	private int id;
	private String messageId;
	private String ackId;
	private Integer userId;
	private String mobileNumber;
	private Date retryTs;
	private int retryCount;
	private String errorCode;
	private String errorDesc;
	private char isRetried;
	

	public NgDlrFailed() {
	}

	public NgDlrFailed(int id, String messageId, String ackId, String mobileNumber, Date retryTs, int retryCount, char isRetried) {
		this.id = id;
		this.messageId = messageId;
		this.ackId = ackId;
		this.mobileNumber = mobileNumber;
		this.retryTs = retryTs;
		this.retryCount = retryCount;
		this.isRetried = isRetried;
	}

	public NgDlrFailed(int id, String messageId, String ackId, Integer userId, String mobileNumber, Date retryTs,
			int retryCount, String errorCode, String errorDesc, char isRetried) {
		this.id = id;
		this.messageId = messageId;
		this.ackId = ackId;
		this.userId = userId;
		this.mobileNumber = mobileNumber;
		this.retryTs = retryTs;
		this.retryCount = retryCount;
		this.errorCode = errorCode;
		this.errorDesc = errorDesc;
		this.isRetried = isRetried;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "message_id", nullable = false, length = 45)
	public String getMessageId() {
		return this.messageId;
	}

	public void setMessageId(String messageId) {
		this.messageId = messageId;
	}

	@Column(name = "ack_id", nullable = false, length = 45)
	public String getAckId() {
		return this.ackId;
	}

	public void setAckId(String ackId) {
		this.ackId = ackId;
	}

	@Column(name = "user_id")
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Column(name = "mobile_number", nullable = false, length = 45)
	public String getMobileNumber() {
		return this.mobileNumber;
	}

	public void setMobileNumber(String mobileNumber) {
		this.mobileNumber = mobileNumber;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "retry_ts", nullable = false, length = 19)
	public Date getRetryTs() {
		return this.retryTs;
	}

	public void setRetryTs(Date retryTs) {
		this.retryTs = retryTs;
	}

	@Column(name = "retry_count", nullable = false)
	public int getRetryCount() {
		return this.retryCount;
	}

	public void setRetryCount(int retryCount) {
		this.retryCount = retryCount;
	}

	@Column(name = "error_code", length = 45)
	public String getErrorCode() {
		return this.errorCode;
	}

	public void setErrorCode(String errorCode) {
		this.errorCode = errorCode;
	}

	@Column(name = "error_desc", length = 100)
	public String getErrorDesc() {
		return this.errorDesc;
	}

	public void setErrorDesc(String errorDesc) {
		this.errorDesc = errorDesc;
	}

	@Column(name = "is_retried", length = 1)
	public char getIsRetried() {
		return isRetried;
	}

	public void setIsRetried(char isRetried) {
		this.isRetried = isRetried;
	}


}
