package com.noesis.domain.persistence;
// Generated 21 Aug, 2018 4:46:47 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NgDlrCurrDate generated by hbm2java
 */
@Entity
@Table(name = "ng_dlr_curr_date", catalog = "genesis")
public class NgDlrCurrDate implements java.io.Serializable {

	private Integer id;
	private int messageId;
	private Integer ackId;
	private String userName;
	private int mobileNumber;
	private Date receivedTs;
	private Date deliveredTs;
	private Integer statusId;
	private String statusDesc;
	private Integer errorCode;
	private String errorDesc;
	private String carrierAckid;
	private String senderId;
	private Integer carrierId;
	private Integer circleId;
	private Integer routeId;
	private String messageSource;
	private Integer failedRetryCount;
	private Integer operatorErrorCode;
	private String operatorErrorDesc;

	public NgDlrCurrDate() {
	}

	public NgDlrCurrDate(int messageId, String userName, int mobileNumber, Date receivedTs, Date deliveredTs,
			String messageSource) {
		this.messageId = messageId;
		this.userName = userName;
		this.mobileNumber = mobileNumber;
		this.receivedTs = receivedTs;
		this.deliveredTs = deliveredTs;
		this.messageSource = messageSource;
	}

	public NgDlrCurrDate(int messageId, Integer ackId, String userName, int mobileNumber, Date receivedTs,
			Date deliveredTs, Integer statusId, String statusDesc, Integer errorCode, String errorDesc,
			String carrierAckid, String senderId, Integer carrierId, Integer circleId, Integer routeId,
			String messageSource, Integer failedRetryCount, Integer operatorErrorCode, String operatorErrorDesc) {
		this.messageId = messageId;
		this.ackId = ackId;
		this.userName = userName;
		this.mobileNumber = mobileNumber;
		this.receivedTs = receivedTs;
		this.deliveredTs = deliveredTs;
		this.statusId = statusId;
		this.statusDesc = statusDesc;
		this.errorCode = errorCode;
		this.errorDesc = errorDesc;
		this.carrierAckid = carrierAckid;
		this.senderId = senderId;
		this.carrierId = carrierId;
		this.circleId = circleId;
		this.routeId = routeId;
		this.messageSource = messageSource;
		this.failedRetryCount = failedRetryCount;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "message_id", nullable = false)
	public int getMessageId() {
		return this.messageId;
	}

	public void setMessageId(int messageId) {
		this.messageId = messageId;
	}

	@Column(name = "ack_id")
	public Integer getAckId() {
		return this.ackId;
	}

	public void setAckId(Integer ackId) {
		this.ackId = ackId;
	}

	@Column(name = "user_name", nullable = false, length = 45)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "mobile_number", nullable = false)
	public int getMobileNumber() {
		return this.mobileNumber;
	}

	public void setMobileNumber(int mobileNumber) {
		this.mobileNumber = mobileNumber;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "received_ts", nullable = false, length = 19)
	public Date getReceivedTs() {
		return this.receivedTs;
	}

	public void setReceivedTs(Date receivedTs) {
		this.receivedTs = receivedTs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "delivered_ts", nullable = false, length = 19)
	public Date getDeliveredTs() {
		return this.deliveredTs;
	}

	public void setDeliveredTs(Date deliveredTs) {
		this.deliveredTs = deliveredTs;
	}

	@Column(name = "status_id")
	public Integer getStatusId() {
		return this.statusId;
	}

	public void setStatusId(Integer statusId) {
		this.statusId = statusId;
	}

	@Column(name = "status_desc", length = 100)
	public String getStatusDesc() {
		return this.statusDesc;
	}

	public void setStatusDesc(String statusDesc) {
		this.statusDesc = statusDesc;
	}

	@Column(name = "error_code")
	public Integer getErrorCode() {
		return this.errorCode;
	}

	public void setErrorCode(Integer errorCode) {
		this.errorCode = errorCode;
	}

	@Column(name = "error_desc", length = 50)
	public String getErrorDesc() {
		return this.errorDesc;
	}

	public void setErrorDesc(String errorDesc) {
		this.errorDesc = errorDesc;
	}

	@Column(name = "carrier_ackid", length = 75)
	public String getCarrierAckid() {
		return this.carrierAckid;
	}

	public void setCarrierAckid(String carrierAckid) {
		this.carrierAckid = carrierAckid;
	}

	@Column(name = "sender_id", length = 20)
	public String getSenderId() {
		return this.senderId;
	}

	public void setSenderId(String senderId) {
		this.senderId = senderId;
	}

	@Column(name = "carrier_id")
	public Integer getCarrierId() {
		return this.carrierId;
	}

	public void setCarrierId(Integer carrierId) {
		this.carrierId = carrierId;
	}

	@Column(name = "circle_id")
	public Integer getCircleId() {
		return this.circleId;
	}

	public void setCircleId(Integer circleId) {
		this.circleId = circleId;
	}

	@Column(name = "route_id")
	public Integer getRouteId() {
		return this.routeId;
	}

	public void setRouteId(Integer routeId) {
		this.routeId = routeId;
	}

	@Column(name = "message_source", nullable = false, length = 50)
	public String getMessageSource() {
		return this.messageSource;
	}

	public void setMessageSource(String messageSource) {
		this.messageSource = messageSource;
	}

	@Column(name = "failed_retry_count", nullable = false, length = 50)
	public Integer getFailedRetryCount() {
		return this.failedRetryCount;
	}

	public void setFailedRetryCount(Integer failedRetryCount) {
		this.failedRetryCount = failedRetryCount;
	}

	@Column(name = "operator_error_code")
	public Integer getOperatorErrorCode() {
		return operatorErrorCode;
	}

	public void setOperatorErrorCode(Integer operatorErrorCode) {
		this.operatorErrorCode = operatorErrorCode;
	}

	@Column(name = "operator_error_desc")
	public String getOperatorErrorDesc() {
		return operatorErrorDesc;
	}

	public void setOperatorErrorDesc(String operatorErrorDesc) {
		this.operatorErrorDesc = operatorErrorDesc;
	}

	
}
