package com.noesis.domain.persistence;
// Generated 21 Aug, 2018 4:46:47 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * NgCarrierErrorMaster generated by hbm2java
 */
@Entity
@Table(name = "ng_error_master", catalog = "genesis")
public class NgErrorMaster implements java.io.Serializable {
	
	private static final long serialVersionUID = -6135113457130256182L;

	private Integer errorCode;
	private String errorDesc;
	
	public NgErrorMaster() {
	}

	public NgErrorMaster(Integer errorCode, String errorDesc) {
		this.errorCode = errorCode;
		this.errorDesc = errorDesc;
	}

	@Id
	@Column(name = "error_code", unique = true, nullable = false)
	public Integer getErrorCode() {
		return this.errorCode;
	}

	public void setErrorCode(Integer errorCode) {
		this.errorCode = errorCode;
	}

	@Column(name = "error_desc", length = 50)
	public String getErrorDesc() {
		return this.errorDesc;
	}

	public void setErrorDesc(String errorDesc) {
		this.errorDesc = errorDesc;
	}
}
