package com.noesis.domain.persistence;
// Generated 10 Feb, 2019 3:16:57 PM by Hibernate Tools 5.0.6.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NgFileUploadInfo generated by hbm2java
 */
@Entity
@Table(name = "ng_file_upload_info", catalog = "genesis")
public class NgFileUploadInfo implements java.io.Serializable {

	private Integer id;
	private NgUser ngUser;
	private String originalFileName;
	private String serverFileName;
	private String campaignName;
	private Date createdDate;

	public NgFileUploadInfo() {
	}

	public NgFileUploadInfo(NgUser ngUser, String originalFileName, String serverFileName, String campaignName,
			Date createdDate) {
		this.ngUser = ngUser;
		this.originalFileName = originalFileName;
		this.serverFileName = serverFileName;
		this.campaignName = campaignName;
		this.createdDate = createdDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id")
	public NgUser getNgUser() {
		return this.ngUser;
	}

	public void setNgUser(NgUser ngUser) {
		this.ngUser = ngUser;
	}

	@Column(name = "original_file_name", length = 250)
	public String getOriginalFileName() {
		return this.originalFileName;
	}

	public void setOriginalFileName(String originalFileName) {
		this.originalFileName = originalFileName;
	}

	@Column(name = "server_file_name", length = 250)
	public String getServerFileName() {
		return this.serverFileName;
	}

	public void setServerFileName(String serverFileName) {
		this.serverFileName = serverFileName;
	}

	@Column(name = "campaign_name", length = 250)
	public String getCampaignName() {
		return this.campaignName;
	}

	public void setCampaignName(String campaignName) {
		this.campaignName = campaignName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

}
