package com.noesis.domain.persistence;
// Generated 31 Jul, 2018 12:08:37 AM by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * NgGlobalBlackList generated by hbm2java
 */
@Entity
@Table(name = "ng_global_black_list", catalog = "genesis")
public class NgGlobalBlackList implements java.io.Serializable {

	private static final long serialVersionUID = -3316939858121588490L;
	private int id;
	private String phoneNumber;
	private String createdDate;
	// black list start
	@Column(name = "description", length = 255)
	private String description;
	// black list end
	
	
	public NgGlobalBlackList() {
	}

	public NgGlobalBlackList(int id) {
		this.id = id;
	}

	public NgGlobalBlackList(int id, String phoneNumber, String createdDate,String description) {
		this.id = id;
		this.phoneNumber = phoneNumber;
		this.createdDate = createdDate;
		this.description = description;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "phone_number", length = 45)
	public String getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	@Column(name = "created_date", length = 45)
	public String getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(String createdDate) {
		this.createdDate = createdDate;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}
	
}
