package com.noesis.domain.persistence;
// Generated 9 Jan, 2019 9:23:21 PM by Hibernate Tools 5.0.6.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NgUserPremiumList generated by hbm2java
 */
@Entity
@Table(name = "ng_global_premium_list", catalog = "genesis")
public class NgGlobalPremiumList implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int id;
	private String premiumNumber;
	private Date createdDate;
	
	public NgGlobalPremiumList() {
	}

	public NgGlobalPremiumList(int id) {
		this.id = id;
	}

	public NgGlobalPremiumList(int id, String premiumNumber, String description, Date createdDate,
			Date updatedDate) {
		this.id = id;
		this.premiumNumber = premiumNumber;
		this.createdDate = createdDate;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "premium_number", length = 45)
	public String getPremiumNumber() {
		return this.premiumNumber;
	}

	public void setPremiumNumber(String premiumNumber) {
		this.premiumNumber = premiumNumber;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", length = 19)
	public Date getCreatedDate() {
		return createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}
}
