package com.noesis.domain.persistence;
// Generated 31 Jul, 2018 12:08:37 AM by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * NgAccountType generated by hbm2java
 */
@Entity
@Table(name = "ng_global_dnd_list", catalog = "genesis")
public class NgGlobalDndList implements java.io.Serializable {

	private static final long serialVersionUID = -3316939858121588490L;
	private int id;
	private String phoneNumber;
	private String optInDate;
	private String optOutDate;
	
	public NgGlobalDndList() {
	}

	public NgGlobalDndList(int id) {
		this.id = id;
	}

	public NgGlobalDndList(int id, String phoneNumber, String optInDate, String optOutDate) {
		this.id = id;
		this.phoneNumber = phoneNumber;
		this.optInDate = optInDate;
		this.optOutDate = optOutDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "phone_number", length = 45)
	public String getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	@Column(name = "opt_in_date", length = 45)
	public String getOptInDate() {
		return this.optInDate;
	}

	public void setOptInDate(String optInDate) {
		this.optInDate = optInDate;
	}

	@Column(name = "opt_out_date", length = 45)
	public String getOptOutDate() {
		return this.optOutDate;
	}

	public void setOptOutDate(String optOutDate) {
		this.optOutDate = optOutDate;
	}
}
