package com.noesis.domain.persistence;
// Generated 31 Jul, 2018 12:08:37 AM by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * NgGlobalBlackList generated by hbm2java
 */
@Entity
@Table(name = "ng_global_sender_id_black_list", catalog = "genesis")
public class NgGlobalSenderIdBlackList implements java.io.Serializable {

	private static final long serialVersionUID = -3316939858121588490L;
	private int id;
	private String senderId;
	private String createdDate;
	
	
	public NgGlobalSenderIdBlackList() {
	}

	public NgGlobalSenderIdBlackList(int id) {
		this.id = id;
	}

	public NgGlobalSenderIdBlackList(int id, String senderId, String createdDate) {
		this.id = id;
		this.senderId = senderId;
		this.createdDate = createdDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "sender_id", length = 45)
	public String getSenderId() {
		return this.senderId;
	}

	public void setSenderId(String senderId) {
		this.senderId = senderId;
	}

	@Column(name = "created_date", length = 45)
	public String getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(String createdDate) {
		this.createdDate = createdDate;
	}
}
