package com.noesis.domain.persistence;
// Generated 11 Feb, 2019 12:48:00 AM by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonBackReference;

/**
 * NgGroup generated by hbm2java
 */
@Entity
@Table(name = "ng_group_number_details", catalog = "genesis")
public class NgGroupNumberDetails implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer id;
	private NgGroup ngGroup;
	private String groupName;
	private String contactName;
	private String contactNumber;
	

	public NgGroupNumberDetails() {
	}

	public NgGroupNumberDetails(NgGroup ngGroup, String groupName, String contactName, String contactNumber) {
		super();
		this.ngGroup = ngGroup;
		this.groupName = groupName;
		this.contactName = contactName;
		this.contactNumber = contactNumber;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "group_name", length = 100)
	public String getGroupName() {
		return this.groupName;
	}

	public void setGroupName(String groupName) {
		this.groupName = groupName;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "group_id", nullable = false, updatable = false, insertable = true)
	@JsonBackReference
	public NgGroup getNgGroup() {
		return this.ngGroup;
	}

	public void setNgGroup(NgGroup ngGroup) {
		this.ngGroup = ngGroup;
	}

	@Column(name = "contact_name", length = 100)
	public String getContactName() {
		return contactName;
	}

	public void setContactName(String contactName) {
		this.contactName = contactName;
	}

	@Column(name = "contact_number", length = 100)
	public String getContactNumber() {
		return contactNumber;
	}

	public void setContactNumber(String contactNumber) {
		this.contactNumber = contactNumber;
	}



}
