package com.noesis.domain.persistence;
// Generated 18 Dec, 2018 8:18:51 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * NgKannelInfo generated by hbm2java
 */
@Entity
@Table(name = "ng_kannel_info", catalog = "genesis")
public class NgKannelInfo implements java.io.Serializable {

	private Integer id;
	private Integer userId;
	private String kannelName;
	private char isActive;
	private int maxTps;
	private String kannelUrl;
	private String kannelMessageType;
	private String dlrUrl;

	public NgKannelInfo() {
	}

	public NgKannelInfo(Integer userId, String kannelName, char isActive, int maxTps, String kannelUrl, String kannelMessageType,
			String dlrUrl) {
		this.userId = userId;
		this.kannelName = kannelName;
		this.isActive = isActive;
		this.maxTps = maxTps;
		this.kannelUrl = kannelUrl;
		this.kannelMessageType = kannelMessageType;
		this.dlrUrl = dlrUrl;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}
	
	@Column(name = "user_id", unique = true, nullable = false)
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Column(name = "kannel_name", nullable = false, length = 45)
	public String getKannelName() {
		return this.kannelName;
	}

	public void setKannelName(String kannelName) {
		this.kannelName = kannelName;
	}

	@Column(name = "is_active", nullable = false, length = 1)
	public char getIsActive() {
		return this.isActive;
	}

	public void setIsActive(char isActive) {
		this.isActive = isActive;
	}

	@Column(name = "max_tps", nullable = false)
	public int getMaxTps() {
		return this.maxTps;
	}

	public void setMaxTps(int maxTps) {
		this.maxTps = maxTps;
	}

	@Column(name = "kannel_url", nullable = false, length = 5000)
	public String getKannelUrl() {
		return this.kannelUrl;
	}

	public void setKannelUrl(String kannelUrl) {
		this.kannelUrl = kannelUrl;
	}

	@Column(name = "kannel_message_type", nullable = false, length = 45)
	public String getKannelMessageType() {
		return this.kannelMessageType;
	}

	public void setKannelMessageType(String kannelMessageType) {
		this.kannelMessageType = kannelMessageType;
	}

	@Column(name = "dlr_url", nullable = false, length = 5000)
	public String getDlrUrl() {
		return this.dlrUrl;
	}

	public void setDlrUrl(String dlrUrl) {
		this.dlrUrl = dlrUrl;
	}

	@Override
	public String toString() {
		return "NgKannelInfo [id=" + id + ", userId=" + userId +", kannelName=" + kannelName + ", maxTps=" + maxTps + ", kannelMessageType="
				+ kannelMessageType + "]";
	}
}
