package com.noesis.domain.persistence;
// Generated 18 Dec, 2018 8:18:51 PM by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * NgKannelGroupMapping generated by hbm2java
 */
@Entity
@Table(name = "ng_kannel_group_mapping_info", catalog = "genesis")
public class NgKannelGroupMappingInfo implements java.io.Serializable {
	
	private static final long serialVersionUID = 1L;

	private Integer id;
	private Integer groupId;
	private Integer kannelId;
	private String kannelName;
	private Integer trafficDistribution;

	public NgKannelGroupMappingInfo() {
	}

	public NgKannelGroupMappingInfo(Integer id, Integer groupId, Integer kannelId, String kannelName, Integer trafficDistribution) {
		this.id = id;
		this.groupId = groupId;
		this.kannelId = kannelId;
		this.kannelName = kannelName;
		this.trafficDistribution = trafficDistribution;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "group_id", nullable = false)
	public Integer getGroupId() {
		return this.groupId;
	}

	public void setGroupId(Integer groupId) {
		this.groupId = groupId;
	}

	@Column(name = "kannel_id", nullable = false, length = 11)
	public Integer getKannelId() {
		return this.kannelId;
	}

	public void setKannelId(Integer kannelId) {
		this.kannelId = kannelId;
	}

	@Column(name = "traffic_distribution", length = 11)
	public Integer getTrafficDistribution() {
		return this.trafficDistribution;
	}

	public void setTrafficDistribution(Integer trafficDistribution) {
		this.trafficDistribution = trafficDistribution;
	}

	@Column(name = "kannel_name", nullable = false, length = 100)
	public String getKannelName() {
		return kannelName;
	}

	public void setKannelName(String kannelName) {
		this.kannelName = kannelName;
	}

	
}
