package com.noesis.domain.persistence;
// Generated 18 Dec, 2018 8:18:51 PM by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * NgKannelGroupMapping generated by hbm2java
 */
@Entity
@Table(name = "ng_kannel_group_mapping", catalog = "genesis")
public class NgKannelGroupMapping implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private int groupId;
	private String kannelId;
	private String kannelAllowedTps;

	public NgKannelGroupMapping() {
	}

	public NgKannelGroupMapping(int id, int groupId, String kannelId) {
		this.id = id;
		this.groupId = groupId;
		this.kannelId = kannelId;
	}

	public NgKannelGroupMapping(int id, int groupId, String kannelId, String kannelAllowedTps) {
		this.id = id;
		this.groupId = groupId;
		this.kannelId = kannelId;
		this.kannelAllowedTps = kannelAllowedTps;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "group_id", nullable = false)
	public int getGroupId() {
		return this.groupId;
	}

	public void setGroupId(int groupId) {
		this.groupId = groupId;
	}

	@Column(name = "kannel_id", nullable = false, length = 50)
	public String getKannelId() {
		return this.kannelId;
	}

	public void setKannelId(String kannelId) {
		this.kannelId = kannelId;
	}

	@Column(name = "kannel_allowed_tps", length = 50)
	public String getKannelAllowedTps() {
		return this.kannelAllowedTps;
	}

	public void setKannelAllowedTps(String kannelAllowedTps) {
		this.kannelAllowedTps = kannelAllowedTps;
	}

}
