package com.noesis.domain.persistence;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;

/**
 * NgGroup generated by hbm2java
 */
@Entity
@Table(name = "ng_message_charset", catalog = "genesis")
public class NgMessageCharset implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer id;
	private String charsetName;
	private String charsetValue;

	public NgMessageCharset() {
	}

	public NgMessageCharset(Integer id, String charsetName, String charsetValue) {
		super();
		this.id = id;
		this.charsetName = charsetName;
		this.charsetValue = charsetValue;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "charset_name", unique = true, nullable = false)
	public String getCharsetName() {
		return charsetName;
	}

	public void setCharsetName(String charsetName) {
		this.charsetName = charsetName;
	}

	@Column(name = "charset_value", unique = true, nullable = false)
	public String getCharsetValue() {
		return charsetValue;
	}

	public void setCharsetValue(String charsetValue) {
		this.charsetValue = charsetValue;
	}

}
