package com.noesis.domain.persistence;
// Generated 31 Jul, 2018 12:08:37 AM by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * NgMessageFilterContent generated by hbm2java
 */
@Entity
@Table(name = "ng_message_filter_content", catalog = "genesis")
public class NgMessageFilterContent implements java.io.Serializable {

	private static final long serialVersionUID = 3916268371613849585L;
	private int id;
	private String keyword;

	public NgMessageFilterContent() {
	}

	public NgMessageFilterContent(int id) {
		this.id = id;
	}

	public NgMessageFilterContent(int id, String keyword) {
		this.id = id;
		this.keyword = keyword;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "keyword", length = 45)
	public String getKeyword() {
		return this.keyword;
	}

	public void setKeyword(String keyword) {
		this.keyword = keyword;
	}

}
