package com.noesis.domain.persistence;
// Generated 31 Jul, 2018 12:08:37 AM by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * NgMessageType generated by hbm2java
 */
@Entity
@Table(name = "ng_message_type", catalog = "genesis")
public class NgMessageType implements java.io.Serializable {

	private static final long serialVersionUID = -8906520971652833648L;
	private int id;
	private String code;
	private String value;
	private String displayName;
	private String description;
	private Set<NgUserTemplateMap> ngUserTemplateMaps = new HashSet<NgUserTemplateMap>(0);
	private Set<NgUser> ngUsers = new HashSet<NgUser>(0);

	public NgMessageType() {
	}

	public NgMessageType(int id) {
		this.id = id;
	}

	public NgMessageType(int id, String code, String value, String displayName, String description,
			Set<NgUserTemplateMap> ngUserTemplateMaps, Set<NgUser> ngUsers) {
		this.id = id;
		this.code = code;
		this.value = value;
		this.displayName = displayName;
		this.description = description;
		this.ngUserTemplateMaps = ngUserTemplateMaps;
		this.ngUsers = ngUsers;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "code", length = 45)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "value", length = 45)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	@Column(name = "display_name", length = 45)
	public String getDisplayName() {
		return this.displayName;
	}

	public void setDisplayName(String displayName) {
		this.displayName = displayName;
	}

	@Column(name = "description", length = 45)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ngMessageType")
	public Set<NgUserTemplateMap> getNgUserTemplateMaps() {
		return this.ngUserTemplateMaps;
	}

	public void setNgUserTemplateMaps(Set<NgUserTemplateMap> ngUserTemplateMaps) {
		this.ngUserTemplateMaps = ngUserTemplateMaps;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ngMessageType")
	public Set<NgUser> getNgUsers() {
		return this.ngUsers;
	}

	public void setNgUsers(Set<NgUser> ngUsers) {
		this.ngUsers = ngUsers;
	}

}
