package com.noesis.domain.persistence;
// Generated 21 Aug, 2018 4:46:47 PM by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.sql.Timestamp;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * NgMisCurrDate generated by hbm2java
 */
@Entity
@Table(name = "ng_mis_curr_date", catalog = "genesis")
public class NgMisMessage implements java.io.Serializable {

	private static final long serialVersionUID = -6135113457130256182L;

	private Integer id;
	private String messageId;
	private String ackId;
	private int userId;
	private Timestamp receivedTs;
	private String status;
	private Timestamp sentTs;
	private String mobileNumber;
	private String messageText;
	private String udh;
	private String messageType;
	private String messageSource;
	private String senderId;
	private Integer kannelId;
	private Integer carrierId;
	private Integer circleId;
	private Integer routeId;
	private Integer groupId;
	private String errorCode;
	private String errorDesc;
	private Integer messageClass;
	private String originalMessageId;
	private Integer priority;
	private String fullMsg;
	private Integer splitCount;
	private Integer failedRetryCount;
	private String entityId;
	private String templateId;
	private String campaignName;
	private Integer campaignId;
	private String campaignTime;
	private String kannelName;
	private String circleName;

	private String carrierName;

	public NgMisMessage() {
	}

	public NgMisMessage(String messageId, int userId, Timestamp receivedTs, String status, Timestamp sentTs,
			String mobileNumber, String messageText, String messageType, String messageSource) {
		this.messageId = messageId;
		this.userId = userId;
		this.receivedTs = receivedTs;
		this.status = status;
		this.sentTs = sentTs;
		this.mobileNumber = mobileNumber;
		this.messageText = messageText;
		this.messageType = messageType;
		this.messageSource = messageSource;
	}

	public NgMisMessage(String messageId, String ackId, int userId, Timestamp receivedTs, String status,
			Timestamp sentTs, String mobileNumber, String messageText, String udh, String messageType,
			String messageSource, String senderId, Integer kannelId, Integer carrierId, Integer circleId,
			Integer routeId, Integer groupId, String errorCode, String errorDesc, Integer messageClass,
			String originalMessageId, Integer priority, String fullMsg, Integer splitCount, Integer failedRetryCount, String circleName, String carrierName, String templateId) {
		this.messageId = messageId;
		this.ackId = ackId;
		this.userId = userId;
		this.receivedTs = receivedTs;
		this.status = status;
		this.sentTs = sentTs;
		this.mobileNumber = mobileNumber;
		this.messageText = messageText;
		this.udh = udh;
		this.messageType = messageType;
		this.messageSource = messageSource;
		this.senderId = senderId;
		this.kannelId = kannelId;
		this.carrierId = carrierId;
		this.circleId = circleId;
		this.routeId = routeId;
		this.groupId = groupId;
		this.errorCode = errorCode;
		this.errorDesc = errorDesc;
		this.messageClass = messageClass;
		this.originalMessageId = originalMessageId;
		this.priority = priority;
		this.fullMsg = fullMsg;
		this.splitCount = splitCount;
		this.failedRetryCount = failedRetryCount;
		this.circleName = circleName;
		this.carrierName = carrierName;
		this.templateId = templateId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "message_id", nullable = false)
	public String getMessageId() {
		return this.messageId;
	}

	public void setMessageId(String messageId) {
		this.messageId = messageId;
	}

	@Column(name = "ack_id")
	public String getAckId() {
		return this.ackId;
	}

	public void setAckId(String ackId) {
		this.ackId = ackId;
	}

	@Column(name = "user_id", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	// @Temporal(TemporalType.TIMESTAMP)
	@Column(name = "received_ts", nullable = false, length = 19)
	public Timestamp getReceivedTs() {
		return this.receivedTs;
	}

	public void setReceivedTs(Timestamp receivedTs) {
		this.receivedTs = receivedTs;
	}

	@Column(name = "status", nullable = false, length = 45)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	// @Temporal(TemporalType.TIMESTAMP)
	@Column(name = "sent_ts", nullable = false, length = 19)
	public Timestamp getSentTs() {
		return this.sentTs;
	}

	public void setSentTs(Timestamp sentTs) {
		this.sentTs = sentTs;
	}

	@Column(name = "mobile_number", nullable = false)
	public String getMobileNumber() {
		return this.mobileNumber;
	}

	public void setMobileNumber(String mobileNumber) {
		this.mobileNumber = mobileNumber;
	}

	@Column(name = "message_text", nullable = false, length = 10000)
	public String getMessageText() {
		return this.messageText;
	}

	public void setMessageText(String messageText) {
		this.messageText = messageText;
	}

	@Column(name = "udh", length = 200)
	public String getUdh() {
		return this.udh;
	}

	public void setUdh(String udh) {
		this.udh = udh;
	}

	@Column(name = "message_type", nullable = false, length = 45)
	public String getMessageType() {
		return this.messageType;
	}

	public void setMessageType(String messageType) {
		this.messageType = messageType;
	}

	@Column(name = "message_source", nullable = false, length = 45)
	public String getMessageSource() {
		return this.messageSource;
	}

	public void setMessageSource(String messageSource) {
		this.messageSource = messageSource;
	}

	@Column(name = "sender_id", length = 10)
	public String getSenderId() {
		return this.senderId;
	}

	public void setSenderId(String senderId) {
		this.senderId = senderId;
	}

	@Column(name = "kannel_id")
	public Integer getKannelId() {
		return this.kannelId;
	}

	public void setKannelId(Integer kannelId) {
		this.kannelId = kannelId;
	}

	@Column(name = "carrier_id")
	public Integer getCarrierId() {
		return this.carrierId;
	}

	public void setCarrierId(Integer carrierId) {
		this.carrierId = carrierId;
	}

	@Column(name = "circle_id")
	public Integer getCircleId() {
		return this.circleId;
	}

	public void setCircleId(Integer circleId) {
		this.circleId = circleId;
	}

	@Column(name = "route_id")
	public Integer getRouteId() {
		return this.routeId;
	}

	public void setRouteId(Integer routeId) {
		this.routeId = routeId;
	}

	@Column(name = "group_id")
	public Integer getGroupId() {
		return this.groupId;
	}

	public void setGroupId(Integer groupId) {
		this.groupId = groupId;
	}

	@Column(name = "error_code", length = 200)
	public String getErrorCode() {
		return this.errorCode;
	}

	public void setErrorCode(String errorCode) {
		this.errorCode = errorCode;
	}

	@Column(name = "error_desc", length = 500)
	public String getErrorDesc() {
		return this.errorDesc;
	}

	public void setErrorDesc(String errorDesc) {
		this.errorDesc = errorDesc;
	}

	@Column(name = "message_class")
	public Integer getMessageClass() {
		return this.messageClass;
	}

	public void setMessageClass(Integer messageClass) {
		this.messageClass = messageClass;
	}

	@Column(name = "original_message_id")
	public String getOriginalMessageId() {
		return this.originalMessageId;
	}

	public void setOriginalMessageId(String originalMessageId) {
		this.originalMessageId = originalMessageId;
	}

	@Column(name = "priority")
	public Integer getPriority() {
		return this.priority;
	}

	public void setPriority(Integer priority) {
		this.priority = priority;
	}

	@Column(name = "full_msg", length = 40000)
	public String getFullMsg() {
		return this.fullMsg;
	}

	public void setFullMsg(String fullMsg) {
		this.fullMsg = fullMsg;
	}

	@Column(name = "split_count")
	public Integer getSplitCount() {
		return this.splitCount;
	}

	public void setSplitCount(Integer splitCount) {
		this.splitCount = splitCount;
	}

	@Column(name = "failed_retry_count")
	public Integer getFailedRetryCount() {
		return this.failedRetryCount;
	}

	public void setFailedRetryCount(Integer failedRetryCount) {
		this.failedRetryCount = failedRetryCount;
	}

	@Column(name = "entity_id")
	public String getEntityId() {
		return entityId;
	}

	public void setEntityId(String entityId) {
		this.entityId = entityId;
	}

	@Column(name = "template_id")
	public String getTemplateId() {
		return templateId;
	}

	public void setTemplateId(String templateId) {
		this.templateId = templateId;
	}

	@Column(name = "campaign_name")
	public String getCampaignName() {
		return campaignName;
	}

	public void setCampaignName(String campaignName) {
		this.campaignName = campaignName;
	}

	@Column(name = "campaign_id")
	public Integer getCampaignId() {
		return campaignId;
	}

	public void setCampaignId(Integer campaignId) {
		this.campaignId = campaignId;
	}

	@Column(name = "campaign_time")
	public String getCampaignTime() {
		return campaignTime;
	}

	public void setCampaignTime(String campaignTime) {
		this.campaignTime = campaignTime;
	}

	@Column(name = "kannel_name")
	public String getKannelName() {
		return kannelName;
	}

	public void setKannelName(String kannelName) {
		this.kannelName = kannelName;
	}
	
	@Column(name = "circle_name")
	public String getCircleName() {
		return circleName;
	}

	public void setCircleName(String circleName) {
		this.circleName = circleName;
	}
	
	@Column(name = "carrier_name")
	public String getCarrierName() {
		return carrierName;
	}

	public void setCarrierName(String carrierName) {
		this.carrierName = carrierName;
	}

}
