package com.noesis.domain.persistence;
// Generated 10 Oct, 2018 2:27:12 AM by Hibernate Tools 4.3.5.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

import org.springframework.data.annotation.Transient;



/**
 * NgMisLog generated by hbm2java
 */
@Entity
@Table(name = "ng_mis_log", catalog = "genesis")
public class NgMisLog implements java.io.Serializable {

	private static final long serialVersionUID = -3962808326915235967L;
	private String messageId;
	private String userName;
	private String mobileNumber;
	private String senderId;
	private String subStatus;
	private String messageText;
	private Date receivedTs;
	private Date deliveredTs;
	private String deliveryStat;
	private String errorCode;
	private String errorDesc;
	private String kannelName;
	
	@Transient
	private String messageCount;
	
	
	private String circleName;									//Changes for add Circle Name in Detailed Report(Aman)
	
	
	private String carrierName;									//Changes for add Carrier Name in Detailed Report(Aman)
	private String templateId;									//Changes for add TemplateId in Detailed Report(Aman)								

	public NgMisLog() {
	}

	public NgMisLog(String messageId, String mobileNumber, String messageText, Date receivedTs) {
		this.messageId = messageId;
		this.mobileNumber = mobileNumber;
		this.messageText = messageText;
		this.receivedTs = receivedTs;
	}

	public NgMisLog(String messageId, String userName, String mobileNumber, String senderId, String subStatus,
			String messageText, Date receivedTs, Date deliveredTs, String deliveryStat, String errorCode,
			String errorDesc, String kannelName, String circleName, String carrierName, String templateId) {
		this.messageId = messageId;
		this.userName = userName;
		this.mobileNumber = mobileNumber;
		this.senderId = senderId;
		this.subStatus = subStatus;
		this.messageText = messageText;
		this.receivedTs = receivedTs;
		this.deliveredTs = deliveredTs;
		this.deliveryStat = deliveryStat;
		this.errorCode = errorCode;
		this.errorDesc = errorDesc;
		this.kannelName = kannelName;
		this.circleName = circleName;
		this.carrierName = carrierName;
		this.templateId = templateId;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "message_id", nullable = false, length = 50)
	public String getMessageId() {
		return this.messageId;
	}

	public void setMessageId(String messageId) {
		this.messageId = messageId;
	}

	@Column(name = "user_name", length = 45)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "mobile_number", nullable = false, length = 20)
	public String getMobileNumber() {
		return this.mobileNumber;
	}

	public void setMobileNumber(String mobileNumber) {
		this.mobileNumber = mobileNumber;
	}

	@Column(name = "sender_id", length = 10)
	public String getSenderId() {
		return this.senderId;
	}

	public void setSenderId(String senderId) {
		this.senderId = senderId;
	}

	@Column(name = "sub_status", length = 11)
	public String getSubStatus() {
		return this.subStatus;
	}

	public void setSubStatus(String subStatus) {
		this.subStatus = subStatus;
	}

	@Column(name = "message_text", nullable = false, length = 10000)
	public String getMessageText() {
		return this.messageText;
	}

	public void setMessageText(String messageText) {
		this.messageText = messageText;
	}

	@Column(name = "received_ts", nullable = false, length = 19)
	public Date getReceivedTs() {
		return this.receivedTs;
	}

	public void setReceivedTs(Date receivedTs) {
		this.receivedTs = receivedTs;
	}

	@Column(name = "delivered_ts", length = 19)
	public Date getDeliveredTs() {
		return this.deliveredTs;
	}

	public void setDeliveredTs(Date deliveredTs) {
		this.deliveredTs = deliveredTs;
	}

	@Column(name = "delivery_stat", length = 9)
	public String getDeliveryStat() {
		return this.deliveryStat;
	}

	public void setDeliveryStat(String deliveryStat) {
		this.deliveryStat = deliveryStat;
	}

	@Column(name = "error_code", length = 20)
	public String getErrorCode() {
		return this.errorCode;
	}

	public void setErrorCode(String errorCode) {
		this.errorCode = errorCode;
	}

	@Column(name = "error_desc", length = 50)
	public String getErrorDesc() {
		return this.errorDesc;
	}

	public void setErrorDesc(String errorDesc) {
		this.errorDesc = errorDesc;
	}

	
	@Column(name = "Kannel_name", length = 50)
	public String getKannelName() {
		return kannelName;
	}

	public void setKannelName(String kannelName) {
		this.kannelName = kannelName;
	}


	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NgMisLog))
			return false;
		NgMisLog castOther = (NgMisLog) other;

		return ((this.getMessageId() == castOther.getMessageId()) || (this.getMessageId() != null
				&& castOther.getMessageId() != null && this.getMessageId().equals(castOther.getMessageId())))
				&& ((this.getUserName() == castOther.getUserName()) || (this.getUserName() != null
						&& castOther.getUserName() != null && this.getUserName().equals(castOther.getUserName())))
				&& ((this.getMobileNumber() == castOther.getMobileNumber())
						|| (this.getMobileNumber() != null && castOther.getMobileNumber() != null
								&& this.getMobileNumber().equals(castOther.getMobileNumber())))
				&& ((this.getSenderId() == castOther.getSenderId()) || (this.getSenderId() != null
						&& castOther.getSenderId() != null && this.getSenderId().equals(castOther.getSenderId())))
				&& ((this.getSubStatus() == castOther.getSubStatus()) || (this.getSubStatus() != null
						&& castOther.getSubStatus() != null && this.getSubStatus().equals(castOther.getSubStatus())))
				&& ((this.getMessageText() == castOther.getMessageText())
						|| (this.getMessageText() != null && castOther.getMessageText() != null
								&& this.getMessageText().equals(castOther.getMessageText())))
				&& ((this.getReceivedTs() == castOther.getReceivedTs()) || (this.getReceivedTs() != null
						&& castOther.getReceivedTs() != null && this.getReceivedTs().equals(castOther.getReceivedTs())))
				&& ((this.getDeliveredTs() == castOther.getDeliveredTs())
						|| (this.getDeliveredTs() != null && castOther.getDeliveredTs() != null
								&& this.getDeliveredTs().equals(castOther.getDeliveredTs())))
				&& ((this.getDeliveryStat() == castOther.getDeliveryStat())
						|| (this.getDeliveryStat() != null && castOther.getDeliveryStat() != null
								&& this.getDeliveryStat().equals(castOther.getDeliveryStat())))
				&& ((this.getErrorCode() == castOther.getErrorCode()) || (this.getErrorCode() != null
						&& castOther.getErrorCode() != null && this.getErrorCode().equals(castOther.getErrorCode())))
				&& ((this.getErrorDesc() == castOther.getErrorDesc()) || (this.getErrorDesc() != null
						&& castOther.getErrorDesc() != null && this.getErrorDesc().equals(castOther.getErrorDesc())))
				&& ((this.getCircleName() == castOther.getCircleName()) || (this.getCircleName() != null
						&& castOther.getCircleName() != null && this.getCircleName().equals(castOther.getCircleName())))
				&& ((this.getCarrierName() == castOther.getCarrierName()) || (this.getCarrierName() != null
				&& castOther.getCarrierName() != null && this.getCarrierName().equals(castOther.getCarrierName())))
				&& ((this.getTemplateId() == castOther.getCarrierName()) || (this.getCarrierName() != null
				&& castOther.getCarrierName() != null && this.getCarrierName().equals(castOther.getCarrierName())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getMessageId() == null ? 0 : this.getMessageId().hashCode());
		result = 37 * result + (getUserName() == null ? 0 : this.getUserName().hashCode());
		result = 37 * result + (getMobileNumber() == null ? 0 : this.getMobileNumber().hashCode());
		result = 37 * result + (getSenderId() == null ? 0 : this.getSenderId().hashCode());
		result = 37 * result + (getSubStatus() == null ? 0 : this.getSubStatus().hashCode());
		result = 37 * result + (getMessageText() == null ? 0 : this.getMessageText().hashCode());
		result = 37 * result + (getReceivedTs() == null ? 0 : this.getReceivedTs().hashCode());
		result = 37 * result + (getDeliveredTs() == null ? 0 : this.getDeliveredTs().hashCode());
		result = 37 * result + (getDeliveryStat() == null ? 0 : this.getDeliveryStat().hashCode());
		result = 37 * result + (getErrorCode() == null ? 0 : this.getErrorCode().hashCode());
		result = 37 * result + (getErrorDesc() == null ? 0 : this.getErrorDesc().hashCode());
		result = 37 * result + (getCircleName() == null ? 0 : this.getCircleName().hashCode());
		result = 37 * result + (getCarrierName() == null ? 0 : this.getCarrierName().hashCode());
		result = 37 * result + (getTemplateId() == null ? 0 : this.getTemplateId().hashCode());
		return result;
	}

	public String getMessageCount() {
		return messageCount;
	}

	public void setMessageCount(String messageCount) {
		this.messageCount = messageCount;
	}
	
	public String getCircleName() {
		return circleName;
	}

	public void setCircleName(String circleName) {
		this.circleName = circleName;
	}
	
	public String getCarrierName() {
		return carrierName;
	}

	public void setCarrierName(String carrierName) {
		this.carrierName = carrierName;
	}

	public String getTemplateId() {
		return templateId;
	}

	public void setTemplateId(String templateId) {
		this.templateId = templateId;
	}

	public void put(Object column, Object value) {
        if (((String) column).equals("message_id")) {
            setMessageId((String)value);
        } 
    }


}
