package com.noesis.domain.persistence;
// Generated 10 Oct, 2018 1:18:37 AM by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * NgMisData generated by hbm2java
 */
@Entity
@Table(name = "ng_mis_data", catalog = "genesis")
public class NgMisData implements java.io.Serializable {

	private NgMisDataId id;

	public NgMisData() {
	}

	public NgMisData(NgMisDataId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "userName", column = @Column(name = "user_name", nullable = false, length = 45)),
			@AttributeOverride(name = "totalSubmitted", column = @Column(name = "total_submitted", precision = 23, scale = 0)),
			@AttributeOverride(name = "totalRejected", column = @Column(name = "total_rejected", precision = 23, scale = 0)),
			@AttributeOverride(name = "totalDelivered", column = @Column(name = "total_delivered", precision = 23, scale = 0)),
			@AttributeOverride(name = "totalFalied", column = @Column(name = "total_falied", precision = 23, scale = 0)),
			@AttributeOverride(name = "orgId", column = @Column(name = "org_id")) })
	public NgMisDataId getId() {
		return this.id;
	}

	public void setId(NgMisDataId id) {
		this.id = id;
	}

}
