package com.noesis.domain.persistence;
// Generated 31 Jul, 2018 12:08:37 AM by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonBackReference;

/**
 * NgUserCreditMap generated by hbm2java
 */
@Entity
@Table(name = "ng_operator_dlt_fields_mapping", catalog = "genesis")
public class NgOperatorDltFieldsMapping implements java.io.Serializable {

	private static final long serialVersionUID = -419235024451838461L;
	private int id;
	//private NgOperatorInfo ngOperatorInfo;
	private String operatorId;
	private String operatorName;
	private String fileType;
	private String ngFieldName;
	private String dltFieldName;
	private Integer dltFieldNumber;
	
	public NgOperatorDltFieldsMapping() {
	}

	public NgOperatorDltFieldsMapping(int id, String operatorId, String operatorName, String fileType, String ngFieldName, 
			String dltFieldName, Integer dltFieldNumber) {
		this.id = id;
		this.operatorId = operatorId;
		this.operatorName = operatorName;
		this.fileType = fileType;
		this.ngFieldName = ngFieldName;
		this.dltFieldName = dltFieldName;
		this.dltFieldNumber = dltFieldNumber;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	
	@Column(name = "operator_id", nullable = false, length = 50)
	public String getOperatorId() {
		return operatorId;
	}

	public void setOperatorId(String operatorId) {
		this.operatorId = operatorId;
	}

	@Column(name = "operator_name", nullable = false, length = 50)
	public String getOperatorName() {
		return operatorName;
	}

	public void setOperatorName(String operatorName) {
		this.operatorName = operatorName;
	}
	
	@Column(name = "file_type", nullable = false, length = 50)
	public String getFileType() {
		return fileType;
	}

	public void setFileType(String fileType) {
		this.fileType = fileType;
	}

	@Column(name = "ng_field_name", length = 50)
	public String getNgFieldName() {
		return ngFieldName;
	}

	public void setNgFieldName(String ngFieldName) {
		this.ngFieldName = ngFieldName;
	}

	public String getDltFieldName() {
		return this.dltFieldName;
	}

	public void setDltFieldName(String dltFieldName) {
		this.dltFieldName = dltFieldName;
	}
	
	@Column(name = "dlt_field_number", length = 50)
	public Integer getDltFieldNumber() {
		return this.dltFieldNumber;
	}

	public void setDltFieldNumber(Integer dltFieldNumber) {
		this.dltFieldNumber = dltFieldNumber;
	}
	
}
