package com.noesis.domain.persistence;
// Generated 31 Jul, 2018 12:08:37 AM by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonBackReference;

/**
 * NgUserCreditMap generated by hbm2java
 */
@Entity
@Table(name = "ng_operator_info", catalog = "genesis")
public class NgOperatorInfo implements java.io.Serializable {

	private static final long serialVersionUID = -419235024451838461L;
	private int id;
	private String operatorId;
	private String operatorName;
	
	public NgOperatorInfo() {
	}

	public NgOperatorInfo(int id, String operatorId, String operatorName, String fileType, String ngFieldName, 
			String dltFieldName, Integer dltFieldNumber) {
		this.id = id;
		this.operatorId = operatorId;
		this.operatorName = operatorName;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "operator_id", nullable = false, length = 50)
	public String getOperatorId() {
		return operatorId;
	}

	public void setOperatorId(String operatorId) {
		this.operatorId = operatorId;
	}

	@Column(name = "operator_name", nullable = false, length = 50)
	public String getOperatorName() {
		return operatorName;
	}

	public void setOperatorName(String operatorName) {
		this.operatorName = operatorName;
	}

}
