package com.noesis.domain.persistence;
// Generated 31 Jul, 2018 12:08:37 AM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;

/**
 * NgOrganisation generated by hbm2java
 */
@Entity
@Table(name = "ng_organisation", catalog = "genesis", uniqueConstraints = @UniqueConstraint(columnNames = "version"))
public class NgOrganisation implements java.io.Serializable {

	private static final long serialVersionUID = -6135116457130256182L;
	private Integer id;
	private int version;
	private NgBillingCycle ngBillingCycle;
	private NgBillingType ngBillingType;
	private NgStatus ngStatus;
	private String name;
	private String address;
	private String email;
	private String gstNumber;
	private String phone;
	private Date createdDate;
	private Date updatedDate;
	private String updatedBy;
	private Set<NgDepartment> ngDepartments = new HashSet<NgDepartment>(0);
	private Set<NgUser> ngUsers = new HashSet<NgUser>(0);
	private String primaryContact;
	private int paId;
	private int saId;
	private int adId;
	
	public NgOrganisation() {
	}

	public NgOrganisation(NgBillingCycle ngBillingCycle, NgBillingType ngBillingType, NgStatus ngStatus,
			String updatedBy, String primaryContact, int paId, int saId, int adId) {
		this.ngBillingCycle = ngBillingCycle;
		this.ngBillingType = ngBillingType;
		this.ngStatus = ngStatus;
		this.updatedBy = updatedBy;
		this.primaryContact = primaryContact;
		this.paId = paId;
		this.saId = saId;
		this.adId = adId;
	}

	public NgOrganisation(NgBillingCycle ngBillingCycle, NgBillingType ngBillingType, NgStatus ngStatus, String name,
			String address, String email, String gstNumber, String phone, Date createdDate, Date updatedDate,
			String updatedBy, Set<NgDepartment> ngDepartments, Set<NgUser> ngUsers, String primaryContact, int paId, 
			int saId, int adId) {
		this.ngBillingCycle = ngBillingCycle;
		this.ngBillingType = ngBillingType;
		this.ngStatus = ngStatus;
		this.name = name;
		this.address = address;
		this.email = email;
		this.gstNumber = gstNumber;
		this.phone = phone;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
		this.updatedBy = updatedBy;
		this.ngDepartments = ngDepartments;
		this.ngUsers = ngUsers;
		this.primaryContact = primaryContact;
		this.paId = paId;
		this.saId = saId;
		this.adId = adId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Version
	@Column(name = "version", unique = true, nullable = false)
	public int getVersion() {
		return this.version;
	}

	public void setVersion(int version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "billing_cycle", nullable = false)
	public NgBillingCycle getNgBillingCycle() {
		return this.ngBillingCycle;
	}

	public void setNgBillingCycle(NgBillingCycle ngBillingCycle) {
		this.ngBillingCycle = ngBillingCycle;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "billing_type", nullable = false)
	public NgBillingType getNgBillingType() {
		return this.ngBillingType;
	}

	public void setNgBillingType(NgBillingType ngBillingType) {
		this.ngBillingType = ngBillingType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "status", nullable = false)
	public NgStatus getNgStatus() {
		return this.ngStatus;
	}

	public void setNgStatus(NgStatus ngStatus) {
		this.ngStatus = ngStatus;
	}

	@Column(name = "name", length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "address", length = 50)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "email", length = 45)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "gst_number", length = 45)
	public String getGstNumber() {
		return this.gstNumber;
	}

	public void setGstNumber(String gstNumber) {
		this.gstNumber = gstNumber;
	}

	@Column(name = "phone", length = 45)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_date", length = 19)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@Column(name = "updated_by", nullable = false, length = 45)
	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ngOrganisation")
	public Set<NgDepartment> getNgDepartments() {
		return this.ngDepartments;
	}

	public void setNgDepartments(Set<NgDepartment> ngDepartments) {
		this.ngDepartments = ngDepartments;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ngOrganisation")
	public Set<NgUser> getNgUsers() {
		return this.ngUsers;
	}

	public void setNgUsers(Set<NgUser> ngUsers) {
		this.ngUsers = ngUsers;
	}


	@Column(name = "primary_contact", nullable = false, length = 45)
	public String getPrimaryContact() {
		return this.primaryContact;
	}

	public void setPrimaryContact(String primaryContact) {
		this.primaryContact = primaryContact;
	}
	
	@Column(name = "pa_id", nullable = false, length = 11)
	public int getPaId() {
		return this.paId;
	}

	public void setPaId(int paId) {
		this.paId = paId;
	}
	
	@Column(name = "sa_id", nullable = false, length = 11)
	public int getSaId() {
		return this.saId;
	}

	public void setSaId(int saId) {
		this.saId = saId;
	}
	
	@Column(name = "ad_id", nullable = false, length = 11)
	public int getAdId() {
		return this.adId;
	}

	public void setAdId(int adId) {
		this.adId = adId;
	}

}
