package com.noesis.domain.persistence;
// Generated 11 Feb, 2019 12:48:00 AM by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;

/**
 * NgGroup generated by hbm2java
 */
@Entity
@Table(name = "ng_platform_error_codes", catalog = "genesis")
public class NgPlatformErrorCodes implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer id;
	private Integer adId;
	private Integer code;
	private String description;

	public NgPlatformErrorCodes() {
	}

	public NgPlatformErrorCodes(Integer id, Integer adId, Integer code, String description ) {
		this.id = id;
		this.adId = adId;
		this.code = code;
		this.description = description;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "ad_id", length = 11)
	public Integer getAdId() {
		return this.adId;
	}

	public void setAdId(Integer adId) {
		this.adId = adId;
	}

	@Column(name = "code", length = 11)
	public Integer getCode() {
		return this.code;
	}

	public void setCode(Integer code) {
		this.code = code;
	}
	
	@Column(name = "description", length = 250)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}
}
