package com.noesis.domain.persistence;
// Generated 31 Jul, 2018 12:08:37 AM by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * NgUserRole generated by hbm2java
 */
@Entity
@Table(name = "ng_post_cutoff_message_list", catalog = "genesis")
public class NgPostCutoffMessage implements java.io.Serializable {

	private static final long serialVersionUID = 6183408858933902776L;
	private int id;
	private String messageId;
	private String userName;
	private String mobileNumber;
	private String messageObject;

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "message_id", nullable = false)
	public String getMessageId() {
		return messageId;
	}

	public void setMessageId(String messageId) {
		this.messageId = messageId;
	}

	@Column(name = "user_name", nullable = false)
	public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "mobile_number", nullable = false)
	public String getMobileNumber() {
		return mobileNumber;
	}

	public void setMobileNumber(String mobileNumber) {
		this.mobileNumber = mobileNumber;
	}

	@Column(name = "message_object", nullable = false)
	public String getMessageObject() {
		return messageObject;
	}

	public void setMessageObject(String messageObject) {
		this.messageObject = messageObject;
	}
}
