package com.noesis.domain.persistence;
// Generated 26 Nov, 2018 9:56:21 PM by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NgDlrDelivered generated by hbm2java
 */
@Entity
@Table(name = "ng_push_dlr_delivered", catalog = "genesis")
public class NgPushDlrDelivered implements java.io.Serializable {

	private static final long serialVersionUID = 8697043041928183971L;
	private Integer id;
	private String messageId;
	private String ackId;
	private int userId;
	private String mobileNumber;
	private Date sentTs;
	private String pushUrl;
//	// start
//	@Column(name = "split_count", nullable = false, length = 100)
//	private String splitCount;
//	//end

	public NgPushDlrDelivered() {
	}

	public NgPushDlrDelivered(String messageId, int userId, String mobileNumber, Date sentTs, String pushUrl) {
		this.messageId = messageId;
		this.userId = userId;
		this.mobileNumber = mobileNumber;
		this.sentTs = sentTs;
		this.pushUrl = pushUrl;
	}

	public NgPushDlrDelivered(String messageId, String ackId, int userId, String mobileNumber, Date sentTs, String pushUrl) {
		this.messageId = messageId;
		this.ackId = ackId;
		this.userId = userId;
		this.mobileNumber = mobileNumber;
		this.sentTs = sentTs;
		this.pushUrl = pushUrl;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "message_id", nullable = false, length = 45)
	public String getMessageId() {
		return this.messageId;
	}

	public void setMessageId(String messageId) {
		this.messageId = messageId;
	}

	@Column(name = "ack_id", length = 45)
	public String getAckId() {
		return this.ackId;
	}

	public void setAckId(String ackId) {
		this.ackId = ackId;
	}

	@Column(name = "user_id", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "mobile_number", nullable = false, length = 45)
	public String getMobileNumber() {
		return this.mobileNumber;
	}

	public void setMobileNumber(String mobileNumber) {
		this.mobileNumber = mobileNumber;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "sent_ts", nullable = false, length = 19)
	public Date getSentTs() {
		return this.sentTs;
	}

	public void setSentTs(Date sentTs) {
		this.sentTs = sentTs;
	}
	
	@Column(name = "push_url", nullable = false, length = 1500)
	public String getPushUrl() {
		return this.pushUrl;
	}

	public void setPushUrl(String pushUrl) {
		this.pushUrl = pushUrl;
	}
  // start
//	public String getSplitCount() {
//		return splitCount;
//	}
//
//	public void setSplitCount(String splitCount) {
//		this.splitCount = splitCount;
//	}
	// end

}
