package com.noesis.domain.persistence;
// Generated 13 Dec, 2018 1:40:39 AM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * NgRoutingTypeMaster generated by hbm2java
 */
@Entity
@Table(name = "ng_routing_type_master", catalog = "genesis")
public class NgRoutingTypeMaster implements java.io.Serializable {

	private int id;
	private String routingType;
	private int priority;

	public NgRoutingTypeMaster() {
	}

	public NgRoutingTypeMaster(int id, String routingType, int priority) {
		this.id = id;
		this.routingType = routingType;
		this.priority = priority;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "routing_type", nullable = false, length = 100)
	public String getRoutingType() {
		return this.routingType;
	}

	public void setRoutingType(String routingType) {
		this.routingType = routingType;
	}

	@Column(name = "priority", nullable = false)
	public int getPriority() {
		return this.priority;
	}

	public void setPriority(int priority) {
		this.priority = priority;
	}

}
