package com.noesis.domain.persistence;
// Generated 13 Dec, 2018 1:40:39 AM by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * NgRoutingInfo generated by hbm2java
 */
@Entity
@Table(name = "ng_routing_info_trans_promo_dnd", catalog = "genesis")
public class NgRoutingInfoTransPromoDnd implements java.io.Serializable {

	private static final long serialVersionUID = 894310955390894938L;
	private int id;
	private Integer userId;
	private Integer parentUserId;
	private Integer carrierId;
	private Integer circleId;
	private Integer senderId;
	private Integer groupId;

	public NgRoutingInfoTransPromoDnd() {
	}

	public NgRoutingInfoTransPromoDnd(int id) {
		this.id = id;
	}

	public NgRoutingInfoTransPromoDnd(int id, Integer userId, Integer parentUserId, Integer carrierId, Integer circleId,
			Integer senderId, Integer groupId) {
		this.id = id;
		this.userId = userId;
		this.parentUserId = parentUserId;
		this.carrierId = carrierId;
		this.circleId = circleId;
		this.senderId = senderId;
		this.groupId = groupId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "user_id")
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Column(name = "parent_user_id")
	public Integer getParentUserId() {
		return this.parentUserId;
	}

	public void setParentUserId(Integer parentUserId) {
		this.parentUserId = parentUserId;
	}

	@Column(name = "carrier_id")
	public Integer getCarrierId() {
		return this.carrierId;
	}

	public void setCarrierId(Integer carrierId) {
		this.carrierId = carrierId;
	}

	@Column(name = "circle_id")
	public Integer getCircleId() {
		return this.circleId;
	}

	public void setCircleId(Integer circleId) {
		this.circleId = circleId;
	}

	@Column(name = "sender_id")
	public Integer getSenderId() {
		return this.senderId;
	}

	public void setSenderId(Integer senderId) {
		this.senderId = senderId;
	}

	@Column(name = "group_id")
	public Integer getGroupId() {
		return this.groupId;
	}

	public void setGroupId(Integer groupId) {
		this.groupId = groupId;
	}

}
