package com.noesis.domain.persistence;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonBackReference;

/**
 * NgGroup generated by hbm2java
 */
@Entity
@Table(name = "ng_service_sub_type", catalog = "genesis")
public class NgServiceSubType implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer id;
	private NgServiceType ngServiceType;
	private String serviceSubType;
	private String displayCode;
	

	public NgServiceSubType() {
	}

	public NgServiceSubType(NgServiceType ngServiceType, Integer id, Integer serviceTypeId, String serviceSubType, String displayCode) {
		super();
		this.id = id;
		this.ngServiceType = ngServiceType;
		this.serviceSubType = serviceSubType;
		this.displayCode = displayCode;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "service_type_id", nullable = false, updatable = false, insertable = true)
	@JsonBackReference
	public NgServiceType getNgServiceType() {
		return this.ngServiceType;
	}

	public void setNgServiceType(NgServiceType ngServiceType) {
		this.ngServiceType = ngServiceType;
	}

	@Column(name = "service_sub_type", length = 100)
	public String getServiceSubType() {
		return serviceSubType;
	}

	public void setServiceSubType(String serviceSubType) {
		this.serviceSubType = serviceSubType;
	}

	@Column(name = "display_code", length = 100)
	public String getDisplayCode() {
		return displayCode;
	}

	public void setDisplayCode(String displayCode) {
		this.displayCode = displayCode;
	}



}
