package com.noesis.domain.persistence;
// Generated 18 Dec, 2018 8:18:51 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NgKannelInfo generated by hbm2java
 */
@Entity
@Table(name = "ng_short_url_child_mapping", catalog = "genesis")
public class NgShortUrlChildMapping implements java.io.Serializable {
	
	private static final long serialVersionUID = 1676665425599676769L;
	private int id;
	private int userId;
	private Integer parentShortUrlId;
	private String parentShortUrl;
	private String childShortUrl;
	private String childUniqueKey;
	private String mobileNumber;
	private String campaignName;
	private Date createdDate;
	private Date updatedDate;
	private int campaignId;
	private String callbackUrl;
	
	public NgShortUrlChildMapping() {
	}

	public NgShortUrlChildMapping(int id, int userId, Integer parentShortUrlId, String parentShortUrl, String childShortUrl, 
			String childUniqueKey, String mobileNumber, String campaignName, Date createdDate, Date updatedDate, String callbackUrl) {
		this.id = id;
		this.userId = userId;
		this.parentShortUrlId = parentShortUrlId;
		this.parentShortUrl = parentShortUrl;
		this.childShortUrl = childShortUrl;
		this.childUniqueKey = childUniqueKey;
		this.mobileNumber = mobileNumber;
		this.campaignName = campaignName;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
		this.callbackUrl = callbackUrl;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}
	
	@Column(name = "userId", unique = true, nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}
	
	@Column(name = "parent_short_url_id", unique = true, nullable = false, length = 100)
	public Integer getParentShortUrlId() {
		return this.parentShortUrlId;
	}

	public void setParentShortUrlId(Integer parentShortUrlId) {
		this.parentShortUrlId = parentShortUrlId;
	}

	@Column(name = "parent_short_url", nullable = false, length = 100)
	public String getParentShortUrl() {
		return this.parentShortUrl;
	}

	public void setParentShortUrl(String parentShortUrl) {
		this.parentShortUrl = parentShortUrl;
	}
	
	@Column(name = "child_short_url", nullable = false, length = 100)
	public String getChildShortUrl() {
		return this.childShortUrl;
	}

	public void setChildShortUrl(String childShortUrl) {
		this.childShortUrl = childShortUrl;
	}
	
	@Column(name = "child_unique_key", nullable = false, length = 10)
	public String getChildUniqueKey() {
		return this.childUniqueKey;
	}

	public void setChildUniqueKey(String childUniqueKey) {
		this.childUniqueKey = childUniqueKey;
	}
	
	@Column(name = "mobile_number", nullable = false, length = 20)
	public String getMobileNumber() {
		return this.mobileNumber;
	}

	public void setMobileNumber(String mobileNumber) {
		this.mobileNumber = mobileNumber;
	}
	
	@Column(name = "campaign_name", nullable = false, length = 100)
	public String getCampaignName() {
		return this.campaignName;
	}

	public void setCampaignName(String campaignName) {
		this.campaignName = campaignName;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", nullable = false, length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_date", nullable = false, length = 19)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@Column(name = "campaign_id", length = 11)
	public int getCampaignId() {
		return campaignId;
	}

	public void setCampaignId(int campaignId) {
		this.campaignId = campaignId;
	}
	
	@Column(name = "callback_url", length = 11)
	public String getCallbackUrl() {
		return callbackUrl;
	}

	public void setCallbackUrl(String callbackUrl) {
		this.callbackUrl = callbackUrl;
	}

}
