package com.noesis.domain.persistence;
// Generated 18 Dec, 2018 8:18:51 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NgKannelInfo generated by hbm2java
 */
@Entity
@Table(name = "ng_short_url", catalog = "genesis")
public class NgShortUrl implements java.io.Serializable {
	
	private static final long serialVersionUID = 1676665425599676769L;
	private int id;
	private int userId;
	private String name;
	private String longUrl;
	private String shortUrl;
	private String uniqueKey;
	private String callbackUrl;
	private String selectedDomainName;
	private char isActive;
	private char isDynamicAllowed;
	private Date createdDate;
	private Date updatedDate;

	public NgShortUrl() {
	}

	public NgShortUrl(int id, int userId, String name, String longUrl, String shortUrl, String uniqueKey, String callbackUrl, 
			String selectedDomainName, char isActive, char isDynamicAllowed, Date createdDate, Date updatedDate) {
		this.id = id;
		this.userId = userId;
		this.name = name;
		this.longUrl = longUrl;
		this.shortUrl = shortUrl;
		this.uniqueKey = uniqueKey;
		this.callbackUrl = callbackUrl;
		this.selectedDomainName = selectedDomainName;
		this.isActive = isActive;
		this.isDynamicAllowed = isDynamicAllowed;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}
	
	@Column(name = "userId", unique = true, nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "name", nullable = false, length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}
	
	@Column(name = "long_url", nullable = false, length = 1000)
	public String getLongUrl() {
		return this.longUrl;
	}

	public void setLongUrl(String longUrl) {
		this.longUrl = longUrl;
	}
	
	@Column(name = "short_url", nullable = false, length = 100)
	public String getShortUrl() {
		return this.shortUrl;
	}

	public void setShortUrl(String shortUrl) {
		this.shortUrl = shortUrl;
	}
	
	@Column(name = "unique_key", nullable = false, length = 10)
	public String getUniqueKey() {
		return this.uniqueKey;
	}

	public void setUniqueKey(String uniqueKey) {
		this.uniqueKey = uniqueKey;
	}
	
	@Column(name = "callback_url", nullable = false, length = 1000)
	public String getCallbackUrl() {
		return this.callbackUrl;
	}

	public void setCallbackUrl(String callbackUrl) {
		this.callbackUrl = callbackUrl;
	}
	
	@Column(name = "selected_domain_name", nullable = false, length = 25)
	public String getSelectedDomainName() {
		return this.selectedDomainName;
	}

	public void setSelectedDomainName(String selectedDomainName) {
		this.selectedDomainName = selectedDomainName;
	}

	@Column(name = "is_active", nullable = false, length = 1)
	public char getIsActive() {
		return this.isActive;
	}

	public void setIsActive(char isActive) {
		this.isActive = isActive;
	}
	
	@Column(name = "is_dynamic_allowed", nullable = false, length = 1)
	public char getIsDynamicAllowed() {
		return this.isDynamicAllowed;
	}

	public void setIsDynamicAllowed(char isDynamicAllowed) {
		this.isDynamicAllowed = isDynamicAllowed;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", nullable = false, length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_date", nullable = false, length = 19)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

}
