package com.noesis.domain.persistence;
// Generated 31 Jul, 2018 12:08:37 AM by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * NgStatus generated by hbm2java
 */
@Entity
@Table(name = "ng_status", catalog = "genesis")
public class NgStatus implements java.io.Serializable {

	private static final long serialVersionUID = -5334505437360412187L;
	private int id;
	private String code;
	private String displayName;
	private String description;
	private Set<NgOrganisation> ngOrganisations = new HashSet<NgOrganisation>(0);
	private Set<NgDepartment> ngDepartments = new HashSet<NgDepartment>(0);
	private Set<NgUser> ngUsers = new HashSet<NgUser>(0);

	public NgStatus() {
	}

	public NgStatus(int id) {
		this.id = id;
	}

	public NgStatus(int id, String code, String displayName, String description, Set<NgOrganisation> ngOrganisations,
			Set<NgDepartment> ngDepartments, Set<NgUser> ngUsers) {
		this.id = id;
		this.code = code;
		this.displayName = displayName;
		this.description = description;
		this.ngOrganisations = ngOrganisations;
		this.ngDepartments = ngDepartments;
		this.ngUsers = ngUsers;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "code", length = 45)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "display_name", length = 45)
	public String getDisplayName() {
		return this.displayName;
	}

	public void setDisplayName(String displayName) {
		this.displayName = displayName;
	}

	@Column(name = "description", length = 45)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ngStatus")
	public Set<NgOrganisation> getNgOrganisations() {
		return this.ngOrganisations;
	}

	public void setNgOrganisations(Set<NgOrganisation> ngOrganisations) {
		this.ngOrganisations = ngOrganisations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ngStatus")
	public Set<NgDepartment> getNgDepartments() {
		return this.ngDepartments;
	}

	public void setNgDepartments(Set<NgDepartment> ngDepartments) {
		this.ngDepartments = ngDepartments;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ngStatus")
	public Set<NgUser> getNgUsers() {
		return this.ngUsers;
	}

	public void setNgUsers(Set<NgUser> ngUsers) {
		this.ngUsers = ngUsers;
	}

}
