package com.noesis.domain.persistence;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * NgTemplate generated by hbm2java
 */
@Entity
@Table(name = "ng_template_message_fields_mapping", catalog = "genesis")
public class NgTemplateMessageFieldsMapping implements java.io.Serializable {
	
	private static final long serialVersionUID = 1L;
	private Integer id;
	private NgTemplateMessageInfo ngTemplateMessageInfo;
	private String templateParamName;
	private String fileFieldName;
	private Integer fileFieldIndex;
	
	public NgTemplateMessageFieldsMapping() {
	}
	
	public NgTemplateMessageFieldsMapping (NgTemplateMessageInfo ngTemplateMessageInfo, String templateParamName, String fileFieldName, Integer fileFieldIndex) {
		this.ngTemplateMessageInfo = ngTemplateMessageInfo;
		this.templateParamName = templateParamName;
		this.fileFieldName = fileFieldName;
		this.fileFieldIndex = fileFieldIndex;
	}
	
	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "temp_msg_info_id")
	public NgTemplateMessageInfo getNgTemplateMessageInfo() {
		return this.ngTemplateMessageInfo;
	}

	public void setNgTemplateMessageInfo(NgTemplateMessageInfo ngTemplateMessageInfo) {
		this.ngTemplateMessageInfo = ngTemplateMessageInfo;
	}
	
	@Column(name = "temp_param_name", length = 50)
	public String getTemplateParamName() {
		return this.templateParamName;
	}

	public void setTemplateParamName(String templateParamName) {
		this.templateParamName = templateParamName;
	}
	
	@Column(name = "file_field_name", length = 50)
	public String getFileFieldName() {
		return this.fileFieldName;
	}

	public void setFileFieldName(String fileFieldName) {
		this.fileFieldName = fileFieldName;
	}
	
	@Column(name = "file_field_index", length = 11)
	public Integer getFileFieldIndex() {
		return this.fileFieldIndex;
	}

	public void setFileFieldIndex(Integer fileFieldIndex) {
		this.fileFieldIndex = fileFieldIndex;
	}

}
