package com.noesis.domain.persistence;
// Generated 31 Jul, 2018 12:08:37 AM by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Index;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NgUserBlackList generated by hbm2java
 */
@Entity
//@Table(name = "ng_user_black_list", catalog = "genesis")  changes taken from aman  written below
@Table(name = "ng_user_black_list", catalog = "genesis", indexes = {
		@Index(name = "idx_user_id", columnList = "user_id"),
		@Index(name = "idx_black_list_number", columnList = "black_list_number")
})

public class NgUserBlackList implements java.io.Serializable {

	private static final long serialVersionUID = -1935137276345866573L;
	private int id;
	private NgUser ngUser;
	private String blackListNumber;
	private String description;
	private Date createdDate;
	private Date updatedDate;
	
	public NgUserBlackList() {
	}

	public NgUserBlackList(int id, NgUser ngUser) {
		this.id = id;
		this.ngUser = ngUser;
	}

	public NgUserBlackList(int id, NgUser ngUser, String blackListNumber, String description, Date createdDate, Date updatedDate) {
		this.id = id;
		this.ngUser = ngUser;
		this.blackListNumber = blackListNumber;
		this.description = description;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public NgUser getNgUser() {
		return this.ngUser;
	}

	public void setNgUser(NgUser ngUser) {
		this.ngUser = ngUser;
	}

	@Column(name = "black_list_number", length = 45)
	public String getBlackListNumber() {
		return this.blackListNumber;
	}

	public void setBlackListNumber(String blackListNumber) {
		this.blackListNumber = blackListNumber;
	}

	@Column(name = "description", length = 250)
	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", length = 19)
	public Date getCreatedDate() {
		return createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_date", length = 19)
	public Date getUpdatedDate() {
		return updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

}
