package com.noesis.domain.persistence;
// Generated 11 Feb, 2019 12:48:00 AM by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * NgGroup generated by hbm2java
 */
@Entity
@Table(name = "ng_user_last_login_info", catalog = "genesis")
public class NgUserLastLoginInfo implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer id;
	private Integer userId;
	private String appName;
	private Date lastLoginTime;
	private String lastLoginIp;

	public NgUserLastLoginInfo() {
	}

	public NgUserLastLoginInfo(Integer id, Integer userId, String appName, Date lastLoginTime, String lastLoginIp ) {
		this.id = id;
		this.userId = userId;
		this.appName = appName;
		this.lastLoginTime = lastLoginTime;
		this.lastLoginIp = lastLoginIp;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "user_id", length = 11)
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Column(name = "app_name", length = 15)
	public String getAppName() {
		return this.appName;
	}

	public void setAppName(String appName) {
		this.appName = appName;
	}

	@Column(name = "last_login_time", length = 15)
	public Date getLastLoginTime() {
		return this.lastLoginTime;
	}

	public void setLastLoginTime(Date lastLoginTime) {
		this.lastLoginTime = lastLoginTime;
	}
	
	@Column(name = "last_login_ip", length = 20)
	public String getLastLoginIp() {
		return this.lastLoginIp;
	}

	public void setLastLoginIp(String lastLoginIp) {
		this.lastLoginIp = lastLoginIp;
	}
}
