package com.noesis.domain.persistence;
// Generated 31 Jul, 2018 12:08:37 AM by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * NgUserCreditMap generated by hbm2java
 */
@Entity
@Table(name = "ng_user_credit_map", catalog = "genesis")
public class NgUserCreditMap implements java.io.Serializable {

	private static final long serialVersionUID = -419235024451838461L;
	private int id;
	private NgUser ngUser;
	private Integer allocatedCredit;
	private Integer availableCredit;
	private Integer blockedCredit = 0;
	private String comments;
	//private Integer userId;
	
	public NgUserCreditMap() {
	}
	
	/*@Column(name = "user_id")
	public Integer getUserId() {
		return userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}
*/
	public NgUserCreditMap(int id, NgUser ngUser) {
		this.id = id;
		this.ngUser = ngUser;
	}

	public NgUserCreditMap(int id, NgUser ngUser, Integer allocatedCredit, Integer availableCredit, String comments) {
		this.id = id;
		this.ngUser = ngUser;
		this.allocatedCredit = allocatedCredit;
		this.availableCredit = availableCredit;
		this.comments = comments;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@OneToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "user_id", nullable = false)
	public NgUser getNgUser() {
		return this.ngUser;
	}

	public void setNgUser(NgUser ngUser) {
		this.ngUser = ngUser;
	}

	@Column(name = "allocated_credit")
	public Integer getAllocatedCredit() {
		return this.allocatedCredit;
	}

	public void setAllocatedCredit(Integer allocatedCredit) {
		this.allocatedCredit = allocatedCredit;
	}

	@Column(name = "available_credit")
	public Integer getAvailableCredit() {
		return this.availableCredit;
	}

	public void setAvailableCredit(Integer availableCredit) {
		this.availableCredit = availableCredit;
	}

	@Column(name = "comments")
	public String getComments() {
		return comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	@Column(name = "blocked_credit")
	public Integer getBlockedCredit() {
		return this.blockedCredit;
	}

	public void setBlockedCredit(Integer blockedCredit) {
		this.blockedCredit = blockedCredit;
	}
}
