package com.noesis.domain.persistence;
// Generated 15 Jan, 2019 12:21:17 AM by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * NgUserAbusingWordsCategoryMap generated by hbm2java
 */
@Entity
@Table(name = "ng_user_abusing_words_category_map", catalog = "genesis")
public class NgUserAbusingWordsCategoryMap implements java.io.Serializable {

	private Integer id;
	private NgUser ngUser;
	private String category;

	public NgUserAbusingWordsCategoryMap() {
	}

	public NgUserAbusingWordsCategoryMap(NgUser ngUser, String category) {
		this.ngUser = ngUser;
		this.category = category;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public NgUser getNgUser() {
		return this.ngUser;
	}

	public void setNgUser(NgUser ngUser) {
		this.ngUser = ngUser;
	}

	@Column(name = "category", nullable = false, length = 100)
	public String getCategory() {
		return this.category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

}
