package com.noesis.domain.persistence;
// Generated 31 Jul, 2018 12:08:37 AM by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonBackReference;

/**
 * NgUserCreditMap generated by hbm2java
 */
@Entity
@Table(name = "ng_user_sender_id_map", catalog = "genesis")
public class NgUserSenderIdMap implements java.io.Serializable {

	private static final long serialVersionUID = -419235024451838461L;
	private int id;
	private NgUser ngUser;
	private String senderId;
	private char isDefault;
	private char isActive;
	private Date createdDate;
	private Date updatedDate;
	private String updatedBy;
	private char isNonDndNumberAllowed;
	private String entityId;
	private String headerId;
	private NgServiceType ngServiceType;
	private NgServiceSubType ngServiceSubType;
	private String category;
	private String shortCode;
	/*@Transient
	private Integer userId;*/
	
	public NgUserSenderIdMap() {
	}
	
	public NgUserSenderIdMap(int id, NgUser ngUser) {
		this.id = id;
		this.ngUser = ngUser;
	}

	public NgUserSenderIdMap(int id, NgUser ngUser, String senderId, char isDefault, char isActive, Date createdDate, 
			Date updatedDate, String updatedBy, char isNonDndNumberAllowed, String entityId, String headerId, 
			NgServiceType ngServiceType, NgServiceSubType ngServiceSubType, String category) {
		this.id = id;
		this.ngUser = ngUser;
		this.isDefault = isDefault;
		this.isActive = isActive;
		this.senderId = senderId;
		this.isNonDndNumberAllowed = isNonDndNumberAllowed;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
		this.updatedBy = updatedBy;
		this.entityId = entityId;
		this.headerId = headerId;
		this.ngServiceType = ngServiceType;
		this.ngServiceSubType = ngServiceSubType;
		this.category = category;
	}
	
	public NgUserSenderIdMap(int id, NgUser ngUser, String senderId, char isDefault, char isActive, Date createdDate, 
			Date updatedDate, String updatedBy, char isNonDndNumberAllowed, String entityId, String headerId, 
			NgServiceType ngServiceType, NgServiceSubType ngServiceSubType, String category, String shortCode) {
		this.id = id;
		this.ngUser = ngUser;
		this.isDefault = isDefault;
		this.isActive = isActive;
		this.senderId = senderId;
		this.isNonDndNumberAllowed = isNonDndNumberAllowed;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
		this.updatedBy = updatedBy;
		this.entityId = entityId;
		this.headerId = headerId;
		this.ngServiceType = ngServiceType;
		this.ngServiceSubType = ngServiceSubType;
		this.category = category;
		this.shortCode = shortCode;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false, updatable=false, insertable=true)
	@JsonBackReference
	public NgUser getNgUser() {
		return this.ngUser;
	}

	public void setNgUser(NgUser ngUser) {
		this.ngUser = ngUser;
	}

	@Column(name = "sender_id", nullable = false)
	public String getSenderId() {
		return senderId;
	}

	public void setSenderId(String senderId) {
		this.senderId = senderId;
	}

	@Column(name = "is_default", nullable = false, length = 1)
	public char getIsDefault() {
		return isDefault;
	}

	public void setIsDefault(char isDefault) {
		this.isDefault = isDefault;
	}

	@Column(name = "is_active", nullable = false, length = 1)
	public char getIsActive() {
		return isActive;
	}

	public void setIsActive(char isActive) {
		this.isActive = isActive;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_date", length = 19)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}
	
	@Column(name = "updated_by", nullable = false, length = 45)
	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}
	
	
	@Column(name = "is_non_dnd_number_allowed", nullable = false, length = 1)
	public char getIsNonDndNumberAllowed() {
		return isNonDndNumberAllowed;
	}

	public void setIsNonDndNumberAllowed(char isNonDndNumberAllowed) {
		this.isNonDndNumberAllowed = isNonDndNumberAllowed;
	}
	
	@Column(name = "entity_id")
	public String getEntityId() {
		return this.entityId;
	}

	public void setEntityId(String entityId) {
		this.entityId = entityId;
	}
	
	@Column(name = "header_id")
	public String getHeaderId() {
		return this.headerId;
	}

	public void setHeaderId(String headerId) {
		this.headerId = headerId;
	}
	
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "sender_id_type", nullable = false, updatable=false, insertable=true)
	@JsonBackReference
	public NgServiceType getNgServiceType() {
		return this.ngServiceType;
	}

	public void setNgServiceType(NgServiceType ngServiceType) {
		this.ngServiceType = ngServiceType;
	}
	
	@ManyToOne(fetch = FetchType.EAGER)//many to one
	@JoinColumn(name = "sender_id_sub_type", nullable = false, updatable=false, insertable=true)
	@JsonBackReference
	public NgServiceSubType getNgServiceSubType() {
		return this.ngServiceSubType;
	}

	public void setNgServiceSubType(NgServiceSubType ngServiceSubType) {
		this.ngServiceSubType = ngServiceSubType;
	}

	@Column(name = "category", length = 200)
	public String getCategory() {
		return this.category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	@Column(name = "short_code", nullable = false)
		public String getShortCode() {
		return shortCode;
	}

	public void setShortCode(String shortCode) {
		this.shortCode = shortCode;
	}

	@Override
	public String toString() {
		return "NgUserSenderIdMap [id=" + id + ", ngUser=" + ngUser + ", senderId=" + senderId + ", isDefault="
				+ isDefault + ", isActive=" + isActive + ", createdDate=" + createdDate + ", updatedDate=" + updatedDate
				+ ", updatedBy=" + updatedBy + ", isNonDndNumberAllowed=" + isNonDndNumberAllowed + ", entityId="
				+ entityId + ", headerId=" + headerId + ", ngServiceType=" + ngServiceType + ", ngServiceSubType="
				+ ngServiceSubType + ", category=" + category + ", shortCode=" + shortCode + "]";
	}
	
	
}
