package com.noesis.domain.persistence;
// Generated 31 Jul, 2018 12:08:37 AM by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * NgUserRole generated by hbm2java
 */
@Entity
@Table(name = "ng_user_role", catalog = "genesis")
public class NgUserRole implements java.io.Serializable {

	private static final long serialVersionUID = 6183408858933902776L;
	private int id;
	private String userRole;
	private String desc;
	private Set<NgUser> ngUsers = new HashSet<NgUser>(0);

	public NgUserRole() {
	}

	public NgUserRole(int id) {
		this.id = id;
	}

	public NgUserRole(int id, String userRole, String desc, Set<NgUser> ngUsers) {
		this.id = id;
		this.userRole = userRole;
		this.desc = desc;
		this.ngUsers = ngUsers;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "user_role", length = 45)
	public String getUserRole() {
		return this.userRole;
	}

	public void setUserRole(String userRole) {
		this.userRole = userRole;
	}

	@Column(name = "desc", length = 45)
	public String getDesc() {
		return this.desc;
	}

	public void setDesc(String desc) {
		this.desc = desc;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ngUserRole")
	public Set<NgUser> getNgUsers() {
		return this.ngUsers;
	}

	public void setNgUsers(Set<NgUser> ngUsers) {
		this.ngUsers = ngUsers;
	}

}
