package com.noesis.domain.persistence;
// Generated 31 Jul, 2018 12:08:37 AM by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * NgUserDlrConfig generated by hbm2java
 */
@Entity
@Table(name = "ng_user_dlr_config", catalog = "genesis")
public class NgUserDlrConfig implements java.io.Serializable {

	private static final long serialVersionUID = -8779689925611795310L;
	private int id;
	private NgUser ngUser;
	private String dlrUrl;
	private String smppIp;
	private String smppPort;
	private String pushUrl;
	private String pullUrl;

	public NgUserDlrConfig() {
	}

	public NgUserDlrConfig(int id, NgUser ngUser) {
		this.id = id;
		this.ngUser = ngUser;
	}

	public NgUserDlrConfig(int id, NgUser ngUser, String dlrUrl, String smppIp, String smppPort, String pushUrl,
			String pullUrl) {
		this.id = id;
		this.ngUser = ngUser;
		this.dlrUrl = dlrUrl;
		this.smppIp = smppIp;
		this.smppPort = smppPort;
		this.pushUrl = pushUrl;
		this.pullUrl = pullUrl;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public NgUser getNgUser() {
		return this.ngUser;
	}

	public void setNgUser(NgUser ngUser) {
		this.ngUser = ngUser;
	}

	@Column(name = "dlr_url", length = 45)
	public String getDlrUrl() {
		return this.dlrUrl;
	}

	public void setDlrUrl(String dlrUrl) {
		this.dlrUrl = dlrUrl;
	}

	@Column(name = "smpp_ip", length = 45)
	public String getSmppIp() {
		return this.smppIp;
	}

	public void setSmppIp(String smppIp) {
		this.smppIp = smppIp;
	}

	@Column(name = "smpp_port", length = 45)
	public String getSmppPort() {
		return this.smppPort;
	}

	public void setSmppPort(String smppPort) {
		this.smppPort = smppPort;
	}

	@Column(name = "push_url", length = 45)
	public String getPushUrl() {
		return this.pushUrl;
	}

	public void setPushUrl(String pushUrl) {
		this.pushUrl = pushUrl;
	}

	@Column(name = "pull_url", length = 45)
	public String getPullUrl() {
		return this.pullUrl;
	}

	public void setPullUrl(String pullUrl) {
		this.pullUrl = pullUrl;
	}

}
