package com.noesis.domain.persistence;
// Generated 9 Jan, 2019 9:23:21 PM by Hibernate Tools 5.0.6.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NgUserPremiumList generated by hbm2java
 */
@Entity
@Table(name = "ng_user_premium_list", catalog = "genesis")
public class NgUserPremiumList implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int id;
	private NgUser ngUser;
	private String premiumNumber;
	private String description;
	private Date createdDate;
	private Date updatedDate;
	
	@Column(name = "group_id") // used in number  routing requirement    only deployed in uat 
	private Integer groupId;

	public NgUserPremiumList() {
	}

	public NgUserPremiumList(int id) {
		this.id = id;
	}

	public NgUserPremiumList(int id, NgUser ngUser, String premiumNumber, String description, Date createdDate,
			Date updatedDate,Integer groupId) {
		this.id = id;
		this.ngUser = ngUser;
		this.premiumNumber = premiumNumber;
		this.description = description;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
		this. groupId  =  groupId;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id")
	public NgUser getNgUser() {
		return this.ngUser;
	}

	public void setNgUser(NgUser ngUser) {
		this.ngUser = ngUser;
	}

	@Column(name = "premium_number", length = 45)
	public String getPremiumNumber() {
		return this.premiumNumber;
	}

	public void setPremiumNumber(String premiumNumber) {
		this.premiumNumber = premiumNumber;
	}

	@Column(name = "description", length = 250)
	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", length = 19)
	public Date getCreatedDate() {
		return createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_date", length = 19)
	public Date getUpdatedDate() {
		return updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	public Integer getGroupId() {
		return groupId;
	}

	public void setGroupId(Integer groupId) {
		this.groupId = groupId;
	}
	
	

}
