package com.noesis.domain.persistence;
// Generated 18 Dec, 2018 8:18:51 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * NgKannelGroupMapping generated by hbm2java
 */
@Entity
@Table(name = "ng_user_routing_group_mapping", catalog = "genesis")
public class NgUserRoutingGroupMapping implements java.io.Serializable {
	
	private static final long serialVersionUID = 1L;

	private Integer id;
	private Integer userId;
	private Integer groupId;
	private String groupName;

	public NgUserRoutingGroupMapping() {
	}

	public NgUserRoutingGroupMapping(Integer id, Integer userId, Integer groupId, String groupName) {
		this.id = id;
		this.userId = userId;
		this.groupId = groupId;
		this.groupName = groupName;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false, length = 11)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}
	
	@Column(name = "user_id", nullable = false, length = 11)
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Column(name = "group_id", nullable = false, length = 11)
	public Integer getGroupId() {
		return this.groupId;
	}

	public void setGroupId(Integer groupId) {
		this.groupId = groupId;
	}

	@Column(name = "group_name", length = 50)
	public String getGroupName() {
		return this.groupName;
	}

	public void setGroupName(String groupName) {
		this.groupName = groupName;
	}

}
