package com.noesis.domain.persistence;
// Generated 11 Feb, 2019 12:48:00 AM by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;

/**
 * NgUserLogoDetails generated by hbm2java
 */
@Entity
@Table(name = "ng_user_logo_details", catalog = "genesis")
public class NgUserLogoDetails implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int id;
	private int userId;
	private String logoPath;
	private String logoAccessUrl;
	
	public NgUserLogoDetails() {
	}

	public NgUserLogoDetails(int id, int userId, String logoPath) {
		super();
		this.id = id;
		this.userId = userId;
		this.logoPath = logoPath;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "user_id", length = 11)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "logo_path", length = 1000)
	public String getLogoPath() {
		return this.logoPath;
	}

	public void setLogoPath(String logoPath) {
		this.logoPath = logoPath;
	}

	@Column(name = "logo_access_url", length = 2000)
	public String getLogoAccessUrl() {
		return logoAccessUrl;
	}

	public void setLogoAccessUrl(String logoAccessUrl) {
		this.logoAccessUrl = logoAccessUrl;
	}
	
	
}
