package com.noesis.domain.persistence;
// Generated 18 Dec, 2018 8:18:51 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NgKannelInfo generated by hbm2java
 */
@Entity
@Table(name = "ng_user_domain_mapping", catalog = "genesis")
public class NgUserDomainMapping implements java.io.Serializable {
	
	private static final long serialVersionUID = 1676665425599676769L;
	private int id;
	private int userId;
	private String name;
	private String domainName;
	private char isActive;
	private Date createdDate;
	private Date updatedDate;
	private String approvedBy;
	private char platformDefault;
	private char isApproved;

	public NgUserDomainMapping() {
	}

	public NgUserDomainMapping(int id, int userId, String name, String domainName, char isActive, Date createdDate, Date updatedDate,
			String approvedBy, char platformDefault, char isApproved) {
		this.id = id;
		this.userId = userId;
		this.name = name;
		this.domainName = domainName;
		this.isActive = isActive;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
		this.approvedBy = approvedBy;
		this.platformDefault = platformDefault;
		this.isApproved = isApproved;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}
	
	@Column(name = "userId", unique = true, nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}
	
	@Column(name = "name", nullable = false, length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "domain_name", nullable = false, length = 25)
	public String getDomainName() {
		return this.domainName;
	}

	public void setDomainName(String domainName) {
		this.domainName = domainName;
	}

	@Column(name = "is_active", nullable = false, length = 1)
	public char getIsActive() {
		return this.isActive;
	}

	public void setIsActive(char isActive) {
		this.isActive = isActive;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", nullable = false, length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_date", nullable = false, length = 19)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}
	
	@Column(name = "approved_by", nullable = false, length = 100)
	public String getApprovedBy() {
		return this.approvedBy;
	}

	public void setApprovedBy(String approvedBy) {
		this.approvedBy = approvedBy;
	}
	
	@Column(name = "platform_default", nullable = false, length = 1)
	public char getPlatformDefault() {
		return this.platformDefault;
	}

	public void setPlatformDefault(char platformDefault) {
		this.platformDefault = platformDefault;
	}
	
	@Column(name = "is_approved", nullable = false, length = 1)
	public char getIsApproved() {
		return this.isApproved;
	}

	public void setIsApproved(char isApproved) {
		this.isApproved = isApproved;
	}

}
