package com.noesis.domain.persistence;
// Generated 31 Jul, 2018 12:08:37 AM by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * NgUserBlackList generated by hbm2java
 */
@Entity
@Table(name = "ng_user_sender_id_black_list", catalog = "genesis")
public class NgUserSenderIdBlackList implements java.io.Serializable {

	private static final long serialVersionUID = -1935137276345866573L;
	private int id;
	private NgUser ngUser;
	private String senderId;

	public NgUserSenderIdBlackList() {
	}

	public NgUserSenderIdBlackList(int id, NgUser ngUser) {
		this.id = id;
		this.ngUser = ngUser;
	}

	public NgUserSenderIdBlackList(int id, NgUser ngUser, String senderId) {
		this.id = id;
		this.ngUser = ngUser;
		this.senderId = senderId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public NgUser getNgUser() {
		return this.ngUser;
	}

	public void setNgUser(NgUser ngUser) {
		this.ngUser = ngUser;
	}

	@Column(name = "sender_id", length = 45)
	public String getSenderId() {
		return this.senderId;
	}

	public void setSenderId(String senderId) {
		this.senderId = senderId;
	}

}
